// Code generated by scripts/generate.mjs v1.0.0 from contract/schema/1.2.0/values.json; DO NOT EDIT.
package v1_2

import wire "github.com/ruipengliu/lerna/contract/gen/go/v1_2"

type ID = wire.ID
type Revision = wire.Revision
type Time = wire.Time
type Kind = wire.Kind
type OwnerRef = wire.OwnerRef
type ObjectRef = wire.ObjectRef
type ContentRef = wire.ContentRef
type ErrorCode = wire.ErrorCode
type PublicError = wire.PublicError
type MethodName = wire.MethodName
type ProfileName = wire.ProfileName
type ContractVersion = wire.ContractVersion
type TraceContext = wire.TraceContext
type CommandPayload = wire.CommandPayload
type CommandEnvelope = wire.CommandEnvelope
type CommandRef = wire.CommandRef
type CommandGetPayload = wire.CommandGetPayload
type CommandGetRequest = wire.CommandGetRequest
type CommandTarget = wire.CommandTarget
type CommandReceiptAccepted = wire.CommandReceiptAccepted
type CommandReceiptRejected = wire.CommandReceiptRejected

func NewCommandReceiptAccepted(value CommandReceiptAccepted) CommandReceipt {
	return wire.NewCommandReceiptAccepted(value)
}
func NewCommandReceiptRejected(value CommandReceiptRejected) CommandReceipt {
	return wire.NewCommandReceiptRejected(value)
}

type CommandReceipt = wire.CommandReceipt
type CommandProgressNone = wire.CommandProgressNone
type CommandProgressUnavailable = wire.CommandProgressUnavailable

func NewCommandProgressNone(value CommandProgressNone) CommandProgress {
	return wire.NewCommandProgressNone(value)
}
func NewCommandProgressUnavailable(value CommandProgressUnavailable) CommandProgress {
	return wire.NewCommandProgressUnavailable(value)
}
func NewCommandProgressContent(value CommandProgressContent) CommandProgress {
	return wire.NewCommandProgressContent(value)
}

type CommandProgress = wire.CommandProgress
type CommandGetResponseFound = wire.CommandGetResponseFound
type CommandGetResponseNotFound = wire.CommandGetResponseNotFound
type CommandGetResponseGone = wire.CommandGetResponseGone
type CommandGetResponseUnavailable = wire.CommandGetResponseUnavailable
type CommandGetResponseRejected = wire.CommandGetResponseRejected

func NewCommandGetResponseFound(value CommandGetResponseFound) CommandGetResponse {
	return wire.NewCommandGetResponseFound(value)
}
func NewCommandGetResponseNotFound(value CommandGetResponseNotFound) CommandGetResponse {
	return wire.NewCommandGetResponseNotFound(value)
}
func NewCommandGetResponseGone(value CommandGetResponseGone) CommandGetResponse {
	return wire.NewCommandGetResponseGone(value)
}
func NewCommandGetResponseUnavailable(value CommandGetResponseUnavailable) CommandGetResponse {
	return wire.NewCommandGetResponseUnavailable(value)
}
func NewCommandGetResponseRejected(value CommandGetResponseRejected) CommandGetResponse {
	return wire.NewCommandGetResponseRejected(value)
}

type CommandGetResponse = wire.CommandGetResponse
type TransportOutcomeReceived = wire.TransportOutcomeReceived
type TransportOutcomeCommitUnknown = wire.TransportOutcomeCommitUnknown

func NewTransportOutcomeReceived(value TransportOutcomeReceived) TransportOutcome {
	return wire.NewTransportOutcomeReceived(value)
}
func NewTransportOutcomeCommitUnknown(value TransportOutcomeCommitUnknown) TransportOutcome {
	return wire.NewTransportOutcomeCommitUnknown(value)
}

type TransportOutcome = wire.TransportOutcome
type DelegatedSubject = wire.DelegatedSubject
type SubjectBinding = wire.SubjectBinding
type SchemaDigest = wire.SchemaDigest
type MethodSupport = wire.MethodSupport
type NegotiationRequest = wire.NegotiationRequest
type Purpose = wire.Purpose
type ContentTarget = wire.ContentTarget
type ContentRange = wire.ContentRange
type ContentPutPayload = wire.ContentPutPayload
type ContentGetPayload = wire.ContentGetPayload
type ContentPutRequest = wire.ContentPutRequest
type ContentGetRequest = wire.ContentGetRequest
type CommandProgressContent = wire.CommandProgressContent
type ContentGetResponsePreparing = wire.ContentGetResponsePreparing
type ContentGetResponsePublished = wire.ContentGetResponsePublished
type ContentGetResponseFailed = wire.ContentGetResponseFailed
type ContentGetResponseGone = wire.ContentGetResponseGone
type ContentGetResponseUnavailable = wire.ContentGetResponseUnavailable
type ContentGetResponseNotFound = wire.ContentGetResponseNotFound
type ContentGetResponseRejected = wire.ContentGetResponseRejected

func NewContentGetResponsePreparing(value ContentGetResponsePreparing) ContentGetResponse {
	return wire.NewContentGetResponsePreparing(value)
}
func NewContentGetResponsePublished(value ContentGetResponsePublished) ContentGetResponse {
	return wire.NewContentGetResponsePublished(value)
}
func NewContentGetResponseFailed(value ContentGetResponseFailed) ContentGetResponse {
	return wire.NewContentGetResponseFailed(value)
}
func NewContentGetResponseGone(value ContentGetResponseGone) ContentGetResponse {
	return wire.NewContentGetResponseGone(value)
}
func NewContentGetResponseUnavailable(value ContentGetResponseUnavailable) ContentGetResponse {
	return wire.NewContentGetResponseUnavailable(value)
}
func NewContentGetResponseNotFound(value ContentGetResponseNotFound) ContentGetResponse {
	return wire.NewContentGetResponseNotFound(value)
}
func NewContentGetResponseRejected(value ContentGetResponseRejected) ContentGetResponse {
	return wire.NewContentGetResponseRejected(value)
}

type ContentGetResponse = wire.ContentGetResponse
type Value interface {
	ID | Revision | Time | Kind | OwnerRef | ObjectRef | ContentRef | ErrorCode | PublicError | MethodName | ProfileName | ContractVersion | TraceContext | CommandPayload | CommandEnvelope | CommandRef | CommandGetPayload | CommandGetRequest | CommandTarget | CommandReceiptAccepted | CommandReceiptRejected | CommandReceipt | CommandProgressNone | CommandProgressUnavailable | CommandProgress | CommandGetResponseFound | CommandGetResponseNotFound | CommandGetResponseGone | CommandGetResponseUnavailable | CommandGetResponseRejected | CommandGetResponse | TransportOutcomeReceived | TransportOutcomeCommitUnknown | TransportOutcome | DelegatedSubject | SubjectBinding | SchemaDigest | MethodSupport | NegotiationRequest | Purpose | ContentTarget | ContentRange | ContentPutPayload | ContentGetPayload | ContentPutRequest | ContentGetRequest | CommandProgressContent | ContentGetResponsePreparing | ContentGetResponsePublished | ContentGetResponseFailed | ContentGetResponseGone | ContentGetResponseUnavailable | ContentGetResponseNotFound | ContentGetResponseRejected | ContentGetResponse
}
