// Code generated by scripts/generate.mjs v1.0.0 from contract/schema/1.0.0/values.json; DO NOT EDIT.
package contract

import wire "github.com/ruipengliu/lerna/contract/gen/go"

type ID = wire.ID
type Revision = wire.Revision
type Time = wire.Time
type Kind = wire.Kind
type OwnerRef = wire.OwnerRef
type ObjectRef = wire.ObjectRef
type ContentRef = wire.ContentRef
type Amount = wire.Amount
type Gap = wire.Gap
type ReadScope = wire.ReadScope
type CollectionView = wire.CollectionView
type ErrorCode = wire.ErrorCode
type PublicError = wire.PublicError
type MethodName = wire.MethodName
type ProfileName = wire.ProfileName
type ContractVersion = wire.ContractVersion
type TraceContext = wire.TraceContext
type CommandPayload = wire.CommandPayload
type CommandEnvelope = wire.CommandEnvelope
type CommandRef = wire.CommandRef
type CommandGetPayload = wire.CommandGetPayload
type CommandGetRequest = wire.CommandGetRequest
type CommandTarget = wire.CommandTarget
type NextAction = wire.NextAction
type CommandReceiptAccepted = wire.CommandReceiptAccepted
type CommandReceiptApplied = wire.CommandReceiptApplied
type CommandReceiptRejected = wire.CommandReceiptRejected

func NewCommandReceiptAccepted(value CommandReceiptAccepted) CommandReceipt {
	return wire.NewCommandReceiptAccepted(value)
}
func NewCommandReceiptApplied(value CommandReceiptApplied) CommandReceipt {
	return wire.NewCommandReceiptApplied(value)
}
func NewCommandReceiptRejected(value CommandReceiptRejected) CommandReceipt {
	return wire.NewCommandReceiptRejected(value)
}

type CommandReceipt = wire.CommandReceipt
type TaskObjectRef = wire.TaskObjectRef
type CommandProgressNone = wire.CommandProgressNone
type CommandProgressUnavailable = wire.CommandProgressUnavailable
type CommandProgressTask = wire.CommandProgressTask

func NewCommandProgressNone(value CommandProgressNone) CommandProgress {
	return wire.NewCommandProgressNone(value)
}
func NewCommandProgressUnavailable(value CommandProgressUnavailable) CommandProgress {
	return wire.NewCommandProgressUnavailable(value)
}
func NewCommandProgressTask(value CommandProgressTask) CommandProgress {
	return wire.NewCommandProgressTask(value)
}

type CommandProgress = wire.CommandProgress
type CommandGetResponseFound = wire.CommandGetResponseFound
type CommandGetResponseNotFound = wire.CommandGetResponseNotFound
type CommandGetResponseGone = wire.CommandGetResponseGone
type CommandGetResponseUnavailable = wire.CommandGetResponseUnavailable
type CommandGetResponseRejected = wire.CommandGetResponseRejected

func NewCommandGetResponseFound(value CommandGetResponseFound) CommandGetResponse {
	return wire.NewCommandGetResponseFound(value)
}
func NewCommandGetResponseNotFound(value CommandGetResponseNotFound) CommandGetResponse {
	return wire.NewCommandGetResponseNotFound(value)
}
func NewCommandGetResponseGone(value CommandGetResponseGone) CommandGetResponse {
	return wire.NewCommandGetResponseGone(value)
}
func NewCommandGetResponseUnavailable(value CommandGetResponseUnavailable) CommandGetResponse {
	return wire.NewCommandGetResponseUnavailable(value)
}
func NewCommandGetResponseRejected(value CommandGetResponseRejected) CommandGetResponse {
	return wire.NewCommandGetResponseRejected(value)
}

type CommandGetResponse = wire.CommandGetResponse
type TransportOutcomeReceived = wire.TransportOutcomeReceived
type TransportOutcomeCommitUnknown = wire.TransportOutcomeCommitUnknown

func NewTransportOutcomeReceived(value TransportOutcomeReceived) TransportOutcome {
	return wire.NewTransportOutcomeReceived(value)
}
func NewTransportOutcomeCommitUnknown(value TransportOutcomeCommitUnknown) TransportOutcome {
	return wire.NewTransportOutcomeCommitUnknown(value)
}

type TransportOutcome = wire.TransportOutcome
type DelegatedSubject = wire.DelegatedSubject
type SubjectBinding = wire.SubjectBinding
type Value interface {
	ID | Revision | Time | Kind | OwnerRef | ObjectRef | ContentRef | Amount | Gap | ReadScope | CollectionView | ErrorCode | PublicError | MethodName | ProfileName | ContractVersion | TraceContext | CommandPayload | CommandEnvelope | CommandRef | CommandGetPayload | CommandGetRequest | CommandTarget | NextAction | CommandReceiptAccepted | CommandReceiptApplied | CommandReceiptRejected | CommandReceipt | TaskObjectRef | CommandProgressNone | CommandProgressUnavailable | CommandProgressTask | CommandProgress | CommandGetResponseFound | CommandGetResponseNotFound | CommandGetResponseGone | CommandGetResponseUnavailable | CommandGetResponseRejected | CommandGetResponse | TransportOutcomeReceived | TransportOutcomeCommitUnknown | TransportOutcome | DelegatedSubject | SubjectBinding
}
