// Code generated by scripts/generate.mjs v1.0.0 from contract/schema/1.0.0/values.json; DO NOT EDIT.
package contract

import wire "github.com/ruipengliu/lerna/contract/gen/go"

type ID = wire.ID
type Revision = wire.Revision
type Time = wire.Time
type Kind = wire.Kind
type OwnerRef = wire.OwnerRef
type ObjectRef = wire.ObjectRef
type ContentRef = wire.ContentRef
type Amount = wire.Amount
type Gap = wire.Gap
type ReadScope = wire.ReadScope
type CollectionView = wire.CollectionView
type Value interface {
	ID | Revision | Time | Kind | OwnerRef | ObjectRef | ContentRef | Amount | Gap | ReadScope | CollectionView
}
