// Code generated by scripts/generate.mjs v1.0.0 from contract/schema/1.0.0/values.json; DO NOT EDIT.
package contract

import wire "github.com/ruipengliu/lerna/contract/gen/go"

type ID = wire.ID
type Revision = wire.Revision
type Time = wire.Time
type Kind = wire.Kind
type OwnerRef = wire.OwnerRef
type ObjectRef = wire.ObjectRef
type ContentRef = wire.ContentRef
type Amount = wire.Amount
type Gap = wire.Gap
type ReadScope = wire.ReadScope
type CollectionView = wire.CollectionView
type ErrorCode = wire.ErrorCode
type PublicError = wire.PublicError
type MethodName = wire.MethodName
type ProfileName = wire.ProfileName
type ContractVersion = wire.ContractVersion
type TraceContext = wire.TraceContext
type CommandPayload = wire.CommandPayload
type CommandEnvelope = wire.CommandEnvelope
type CommandRef = wire.CommandRef
type CommandGetPayload = wire.CommandGetPayload
type CommandGetRequest = wire.CommandGetRequest
type CommandTarget = wire.CommandTarget
type DelegatedSubject = wire.DelegatedSubject
type SubjectBinding = wire.SubjectBinding
type Value interface {
	ID | Revision | Time | Kind | OwnerRef | ObjectRef | ContentRef | Amount | Gap | ReadScope | CollectionView | ErrorCode | PublicError | MethodName | ProfileName | ContractVersion | TraceContext | CommandPayload | CommandEnvelope | CommandRef | CommandGetPayload | CommandGetRequest | CommandTarget | DelegatedSubject | SubjectBinding
}
