// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: durable.sql

package querygen

import (
	"context"
)

const ClaimCandidates = `-- name: ClaimCandidates :many
SELECT tenant_id,owner_id,kind,responsibility_key,job_id,source_ref,state,due_at,work_revision,lease_epoch,lease_until,holder_id,wait_reason FROM durable_jobs WHERE tenant_id=$1 AND owner_id=$2 AND kind=$3 AND
 ((state IN ('ready','waiting') AND due_at<=(floor(extract(epoch FROM clock_timestamp())*1000)::bigint)) OR (state='leased' AND lease_until<=(floor(extract(epoch FROM clock_timestamp())*1000)::bigint)))
ORDER BY due_at,responsibility_key LIMIT $4 FOR UPDATE SKIP LOCKED
`

type ClaimCandidatesParams struct {
	TenantID string
	OwnerID  string
	Kind     string
	Limit    int32
}

func (q *Queries) ClaimCandidates(ctx context.Context, arg ClaimCandidatesParams) ([]DurableJob, error) {
	rows, err := q.db.QueryContext(ctx, ClaimCandidates,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DurableJob
	for rows.Next() {
		var i DurableJob
		if err := rows.Scan(
			&i.TenantID,
			&i.OwnerID,
			&i.Kind,
			&i.ResponsibilityKey,
			&i.JobID,
			&i.SourceRef,
			&i.State,
			&i.DueAt,
			&i.WorkRevision,
			&i.LeaseEpoch,
			&i.LeaseUntil,
			&i.HolderID,
			&i.WaitReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const DBNow = `-- name: DBNow :one
SELECT (floor(extract(epoch FROM clock_timestamp())*1000)::bigint) AS current_ms
`

func (q *Queries) DBNow(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, DBNow)
	var current_ms int64
	err := row.Scan(&current_ms)
	return current_ms, err
}

const DeleteDone = `-- name: DeleteDone :execrows
DELETE FROM durable_jobs WHERE tenant_id=$1 AND owner_id=$2 AND kind=$3 AND responsibility_key=$4 AND state='done'
`

type DeleteDoneParams struct {
	TenantID          string
	OwnerID           string
	Kind              string
	ResponsibilityKey string
}

func (q *Queries) DeleteDone(ctx context.Context, arg DeleteDoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteDone,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.ResponsibilityKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const HintJob = `-- name: HintJob :exec
UPDATE durable_jobs SET due_at=LEAST(due_at,$5) WHERE tenant_id=$1 AND owner_id=$2 AND kind=$3 AND responsibility_key=$4 AND state<>'done'
`

type HintJobParams struct {
	TenantID          string
	OwnerID           string
	Kind              string
	ResponsibilityKey string
	DueAt             int64
}

func (q *Queries) HintJob(ctx context.Context, arg HintJobParams) error {
	_, err := q.db.ExecContext(ctx, HintJob,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.ResponsibilityKey,
		arg.DueAt,
	)
	return err
}

const LeaseJob = `-- name: LeaseJob :one
UPDATE durable_jobs SET state='leased',holder_id=$4,lease_epoch=lease_epoch+1,lease_until=$5,wait_reason=''
WHERE tenant_id=$1 AND owner_id=$2 AND job_id=$3 RETURNING tenant_id,owner_id,kind,responsibility_key,job_id,source_ref,state,due_at,work_revision,lease_epoch,lease_until,holder_id,wait_reason
`

type LeaseJobParams struct {
	TenantID   string
	OwnerID    string
	JobID      string
	HolderID   string
	LeaseUntil int64
}

func (q *Queries) LeaseJob(ctx context.Context, arg LeaseJobParams) (DurableJob, error) {
	row := q.db.QueryRowContext(ctx, LeaseJob,
		arg.TenantID,
		arg.OwnerID,
		arg.JobID,
		arg.HolderID,
		arg.LeaseUntil,
	)
	var i DurableJob
	err := row.Scan(
		&i.TenantID,
		&i.OwnerID,
		&i.Kind,
		&i.ResponsibilityKey,
		&i.JobID,
		&i.SourceRef,
		&i.State,
		&i.DueAt,
		&i.WorkRevision,
		&i.LeaseEpoch,
		&i.LeaseUntil,
		&i.HolderID,
		&i.WaitReason,
	)
	return i, err
}

const LockJob = `-- name: LockJob :one
SELECT tenant_id,owner_id,kind,responsibility_key,job_id,source_ref,state,due_at,work_revision,lease_epoch,lease_until,holder_id,wait_reason FROM durable_jobs WHERE tenant_id=$1 AND owner_id=$2 AND job_id=$3 FOR UPDATE
`

type LockJobParams struct {
	TenantID string
	OwnerID  string
	JobID    string
}

func (q *Queries) LockJob(ctx context.Context, arg LockJobParams) (DurableJob, error) {
	row := q.db.QueryRowContext(ctx, LockJob, arg.TenantID, arg.OwnerID, arg.JobID)
	var i DurableJob
	err := row.Scan(
		&i.TenantID,
		&i.OwnerID,
		&i.Kind,
		&i.ResponsibilityKey,
		&i.JobID,
		&i.SourceRef,
		&i.State,
		&i.DueAt,
		&i.WorkRevision,
		&i.LeaseEpoch,
		&i.LeaseUntil,
		&i.HolderID,
		&i.WaitReason,
	)
	return i, err
}

const LookupCommand = `-- name: LookupCommand :one
SELECT digest,method,target_id,state,preparation_ref,receipt,decided_type,expires_at,retain_until FROM durable_commands WHERE tenant_id=$1 AND owner_id=$2 AND service_id=$3 AND command_id=$4 FOR UPDATE
`

type LookupCommandParams struct {
	TenantID  string
	OwnerID   string
	ServiceID string
	CommandID string
}

type LookupCommandRow struct {
	Digest         string
	Method         string
	TargetID       string
	State          string
	PreparationRef string
	Receipt        string
	DecidedType    string
	ExpiresAt      int64
	RetainUntil    int64
}

func (q *Queries) LookupCommand(ctx context.Context, arg LookupCommandParams) (LookupCommandRow, error) {
	row := q.db.QueryRowContext(ctx, LookupCommand,
		arg.TenantID,
		arg.OwnerID,
		arg.ServiceID,
		arg.CommandID,
	)
	var i LookupCommandRow
	err := row.Scan(
		&i.Digest,
		&i.Method,
		&i.TargetID,
		&i.State,
		&i.PreparationRef,
		&i.Receipt,
		&i.DecidedType,
		&i.ExpiresAt,
		&i.RetainUntil,
	)
	return i, err
}

const OpenJobs = `-- name: OpenJobs :one
SELECT count(*) AS open_count,COALESCE(min(due_at),0) AS oldest_due FROM durable_jobs WHERE tenant_id=$1 AND owner_id=$2 AND state<>'done'
`

type OpenJobsParams struct {
	TenantID string
	OwnerID  string
}

type OpenJobsRow struct {
	OpenCount int64
	OldestDue interface{}
}

func (q *Queries) OpenJobs(ctx context.Context, arg OpenJobsParams) (OpenJobsRow, error) {
	row := q.db.QueryRowContext(ctx, OpenJobs, arg.TenantID, arg.OwnerID)
	var i OpenJobsRow
	err := row.Scan(&i.OpenCount, &i.OldestDue)
	return i, err
}

const RaiseJob = `-- name: RaiseJob :one
INSERT INTO durable_jobs(tenant_id,owner_id,kind,responsibility_key,job_id,source_ref,state,due_at,work_revision,lease_epoch,lease_until,holder_id,wait_reason) VALUES($1,$2,$3,$4,$5,$6,'ready',$7,1,0,0,'','')
ON CONFLICT(tenant_id,owner_id,kind,responsibility_key) DO UPDATE SET
 work_revision=durable_jobs.work_revision+1,
 due_at=LEAST(durable_jobs.due_at,excluded.due_at),
 state=CASE WHEN durable_jobs.state='leased' THEN 'leased' ELSE 'ready' END,
 wait_reason=''
WHERE durable_jobs.source_ref=excluded.source_ref
RETURNING tenant_id,owner_id,kind,responsibility_key,job_id,source_ref,state,due_at,work_revision,lease_epoch,lease_until,holder_id,wait_reason
`

type RaiseJobParams struct {
	TenantID          string
	OwnerID           string
	Kind              string
	ResponsibilityKey string
	JobID             string
	SourceRef         string
	DueAt             int64
}

func (q *Queries) RaiseJob(ctx context.Context, arg RaiseJobParams) (DurableJob, error) {
	row := q.db.QueryRowContext(ctx, RaiseJob,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.ResponsibilityKey,
		arg.JobID,
		arg.SourceRef,
		arg.DueAt,
	)
	var i DurableJob
	err := row.Scan(
		&i.TenantID,
		&i.OwnerID,
		&i.Kind,
		&i.ResponsibilityKey,
		&i.JobID,
		&i.SourceRef,
		&i.State,
		&i.DueAt,
		&i.WorkRevision,
		&i.LeaseEpoch,
		&i.LeaseUntil,
		&i.HolderID,
		&i.WaitReason,
	)
	return i, err
}

const ReserveCommand = `-- name: ReserveCommand :execrows
INSERT INTO durable_commands(tenant_id,owner_id,service_id,command_id,digest,method,target_id,state,expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,'reserved',$8) ON CONFLICT(tenant_id,service_id,command_id) DO NOTHING
`

type ReserveCommandParams struct {
	TenantID  string
	OwnerID   string
	ServiceID string
	CommandID string
	Digest    string
	Method    string
	TargetID  string
	ExpiresAt int64
}

func (q *Queries) ReserveCommand(ctx context.Context, arg ReserveCommandParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ReserveCommand,
		arg.TenantID,
		arg.OwnerID,
		arg.ServiceID,
		arg.CommandID,
		arg.Digest,
		arg.Method,
		arg.TargetID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SaveCommand = `-- name: SaveCommand :execrows
UPDATE durable_commands SET state=$5,preparation_ref=$6,receipt=$7,decided_type=$8,retain_until=$9 WHERE tenant_id=$1 AND owner_id=$2 AND service_id=$3 AND command_id=$4
`

type SaveCommandParams struct {
	TenantID       string
	OwnerID        string
	ServiceID      string
	CommandID      string
	State          string
	PreparationRef string
	Receipt        string
	DecidedType    string
	RetainUntil    int64
}

func (q *Queries) SaveCommand(ctx context.Context, arg SaveCommandParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, SaveCommand,
		arg.TenantID,
		arg.OwnerID,
		arg.ServiceID,
		arg.CommandID,
		arg.State,
		arg.PreparationRef,
		arg.Receipt,
		arg.DecidedType,
		arg.RetainUntil,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateJob = `-- name: UpdateJob :execrows
UPDATE durable_jobs SET state=$4,due_at=$5,holder_id=$6,lease_until=$7,wait_reason=$8 WHERE tenant_id=$1 AND owner_id=$2 AND job_id=$3
`

type UpdateJobParams struct {
	TenantID   string
	OwnerID    string
	JobID      string
	State      string
	DueAt      int64
	HolderID   string
	LeaseUntil int64
	WaitReason string
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, UpdateJob,
		arg.TenantID,
		arg.OwnerID,
		arg.JobID,
		arg.State,
		arg.DueAt,
		arg.HolderID,
		arg.LeaseUntil,
		arg.WaitReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
