// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querygen

type DurableCommand struct {
	TenantID       string
	OwnerID        string
	ServiceID      string
	CommandID      string
	Digest         string
	Method         string
	TargetID       string
	State          string
	PreparationRef string
	Receipt        string
	DecidedType    string
	ExpiresAt      int64
	RetainUntil    int64
}

type DurableJob struct {
	TenantID          string
	OwnerID           string
	Kind              string
	ResponsibilityKey string
	JobID             string
	SourceRef         string
	State             string
	DueAt             int64
	WorkRevision      int64
	LeaseEpoch        int64
	LeaseUntil        int64
	HolderID          string
	WaitReason        string
}
