// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestrator.sql

package querygen

import (
	"context"
	"encoding/json"
)

const OrchestratorBalances = `-- name: OrchestratorBalances :many
SELECT unit,limit_value,spent,reserved FROM orchestrator_balances WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3 ORDER BY unit LIMIT 101
`

type OrchestratorBalancesParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
}

type OrchestratorBalancesRow struct {
	Unit       string
	LimitValue string
	Spent      string
	Reserved   string
}

func (q *Queries) OrchestratorBalances(ctx context.Context, arg OrchestratorBalancesParams) ([]OrchestratorBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorBalances, arg.TenantID, arg.OwnerID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorBalancesRow
	for rows.Next() {
		var i OrchestratorBalancesRow
		if err := rows.Scan(
			&i.Unit,
			&i.LimitValue,
			&i.Spent,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorBatchLockBalances = `-- name: OrchestratorBatchLockBalances :many
SELECT task_id,unit,limit_value,spent,reserved FROM orchestrator_balances WHERE tenant_id=$1 AND owner_id=$2 AND task_id IN (SELECT jsonb_array_elements_text($3::jsonb)) ORDER BY task_id,unit FOR UPDATE
`

type OrchestratorBatchLockBalancesParams struct {
	TenantID string
	OwnerID  string
	Column3  json.RawMessage
}

type OrchestratorBatchLockBalancesRow struct {
	TaskID     string
	Unit       string
	LimitValue string
	Spent      string
	Reserved   string
}

func (q *Queries) OrchestratorBatchLockBalances(ctx context.Context, arg OrchestratorBatchLockBalancesParams) ([]OrchestratorBatchLockBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorBatchLockBalances, arg.TenantID, arg.OwnerID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorBatchLockBalancesRow
	for rows.Next() {
		var i OrchestratorBatchLockBalancesRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Unit,
			&i.LimitValue,
			&i.Spent,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorBatchLockTasks = `-- name: OrchestratorBatchLockTasks :many
SELECT data FROM orchestrator_tasks WHERE tenant_id=$1 AND owner_id=$2 AND task_id IN (SELECT jsonb_array_elements_text($3::jsonb)) ORDER BY depth,task_id FOR UPDATE
`

type OrchestratorBatchLockTasksParams struct {
	TenantID string
	OwnerID  string
	Column3  json.RawMessage
}

func (q *Queries) OrchestratorBatchLockTasks(ctx context.Context, arg OrchestratorBatchLockTasksParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorBatchLockTasks, arg.TenantID, arg.OwnerID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorCapacityChange = `-- name: OrchestratorCapacityChange :execrows
UPDATE orchestrator_user_capacity SET active_count=active_count+$4 WHERE tenant_id=$1 AND owner_id=$2 AND subject_id=$3 AND active_count+$4 BETWEEN 0 AND $5
`

type OrchestratorCapacityChangeParams struct {
	TenantID      string
	OwnerID       string
	SubjectID     string
	ActiveCount   int64
	ActiveCount_2 int64
}

func (q *Queries) OrchestratorCapacityChange(ctx context.Context, arg OrchestratorCapacityChangeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, OrchestratorCapacityChange,
		arg.TenantID,
		arg.OwnerID,
		arg.SubjectID,
		arg.ActiveCount,
		arg.ActiveCount_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const OrchestratorCapacityCreate = `-- name: OrchestratorCapacityCreate :exec
INSERT INTO orchestrator_user_capacity(tenant_id,owner_id,subject_id,active_count) VALUES($1,$2,$3,0) ON CONFLICT DO NOTHING
`

type OrchestratorCapacityCreateParams struct {
	TenantID  string
	OwnerID   string
	SubjectID string
}

func (q *Queries) OrchestratorCapacityCreate(ctx context.Context, arg OrchestratorCapacityCreateParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorCapacityCreate, arg.TenantID, arg.OwnerID, arg.SubjectID)
	return err
}

const OrchestratorChain = `-- name: OrchestratorChain :many
WITH RECURSIVE chain AS (
 SELECT origin.task_id,origin.parent_task_id,origin.depth,origin.data FROM orchestrator_tasks origin WHERE origin.tenant_id=$1 AND origin.owner_id=$2 AND origin.task_id=$3
 UNION ALL
 SELECT t.task_id,t.parent_task_id,t.depth,t.data FROM orchestrator_tasks t JOIN chain c ON t.task_id=c.parent_task_id WHERE t.tenant_id=$1 AND t.owner_id=$2
) SELECT data FROM chain ORDER BY depth,task_id LIMIT 6
`

type OrchestratorChainParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
}

func (q *Queries) OrchestratorChain(ctx context.Context, arg OrchestratorChainParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorChain, arg.TenantID, arg.OwnerID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorCurrentRecords = `-- name: OrchestratorCurrentRecords :many
SELECT kind,id,task_id,revision,state,current_key,immutable,data FROM orchestrator_records WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3 AND kind=$4 AND current_key<>'' ORDER BY id LIMIT $5
`

type OrchestratorCurrentRecordsParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
	Kind     string
	Limit    int32
}

type OrchestratorCurrentRecordsRow struct {
	Kind       string
	ID         string
	TaskID     string
	Revision   int64
	State      string
	CurrentKey string
	Immutable  bool
	Data       string
}

func (q *Queries) OrchestratorCurrentRecords(ctx context.Context, arg OrchestratorCurrentRecordsParams) ([]OrchestratorCurrentRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorCurrentRecords,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Kind,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorCurrentRecordsRow
	for rows.Next() {
		var i OrchestratorCurrentRecordsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.TaskID,
			&i.Revision,
			&i.State,
			&i.CurrentKey,
			&i.Immutable,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorDeselect = `-- name: OrchestratorDeselect :exec
UPDATE orchestrator_records SET current_key='' WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3 AND kind=$4 AND current_key=$5
`

type OrchestratorDeselectParams struct {
	TenantID   string
	OwnerID    string
	TaskID     string
	Kind       string
	CurrentKey string
}

func (q *Queries) OrchestratorDeselect(ctx context.Context, arg OrchestratorDeselectParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorDeselect,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Kind,
		arg.CurrentKey,
	)
	return err
}

const OrchestratorDeselectKeys = `-- name: OrchestratorDeselectKeys :exec
UPDATE orchestrator_records SET current_key='' WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3 AND kind=$4 AND current_key IN (SELECT jsonb_array_elements_text($5::jsonb))
`

type OrchestratorDeselectKeysParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
	Kind     string
	Column5  json.RawMessage
}

func (q *Queries) OrchestratorDeselectKeys(ctx context.Context, arg OrchestratorDeselectKeysParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorDeselectKeys,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Kind,
		arg.Column5,
	)
	return err
}

const OrchestratorFairCandidates = `-- name: OrchestratorFairCandidates :many
SELECT j.tenant_id,j.owner_id,j.kind,j.responsibility_key,j.job_id,j.source_ref,j.state,j.due_at,j.work_revision,j.lease_epoch,j.lease_until,j.holder_id,j.wait_reason,
 COALESCE(r.subject_id,j.owner_id) AS subject_id,COALESCE(r.task_id,j.source_ref) AS task_id
FROM durable_jobs j LEFT JOIN orchestrator_work_routes r ON r.tenant_id=j.tenant_id AND r.owner_id=j.owner_id AND r.kind=j.kind AND r.responsibility_key=j.responsibility_key
LEFT JOIN orchestrator_schedule_turns u ON u.tenant_id=j.tenant_id AND u.owner_id=j.owner_id AND u.kind=j.kind AND u.dimension='user' AND u.entity_id=COALESCE(r.subject_id,j.owner_id)
LEFT JOIN orchestrator_schedule_turns t ON t.tenant_id=j.tenant_id AND t.owner_id=j.owner_id AND t.kind=j.kind AND t.dimension='task' AND t.entity_id=COALESCE(r.task_id,j.source_ref)
WHERE j.tenant_id=$1 AND j.owner_id=$2 AND j.kind=$3
 AND ((j.state IN ('ready','waiting') AND j.due_at<=(floor(extract(epoch FROM clock_timestamp())*1000)::bigint)) OR (j.state='leased' AND j.lease_until<=(floor(extract(epoch FROM clock_timestamp())*1000)::bigint)))
 AND (r.provider_id IS NULL OR r.provider_id='' OR (SELECT count(*) FROM orchestrator_work_routes pr JOIN durable_jobs pj ON pj.tenant_id=pr.tenant_id AND pj.owner_id=pr.owner_id AND pj.kind=pr.kind AND pj.responsibility_key=pr.responsibility_key WHERE pr.tenant_id=j.tenant_id AND pr.owner_id=j.owner_id AND pr.provider_id=r.provider_id AND pj.state='leased' AND pj.lease_until>(floor(extract(epoch FROM clock_timestamp())*1000)::bigint))<$5)
 AND (r.resource_id IS NULL OR r.resource_id='' OR (SELECT count(*) FROM orchestrator_work_routes rr JOIN durable_jobs rj ON rj.tenant_id=rr.tenant_id AND rj.owner_id=rr.owner_id AND rj.kind=rr.kind AND rj.responsibility_key=rr.responsibility_key WHERE rr.tenant_id=j.tenant_id AND rr.owner_id=j.owner_id AND rr.resource_id=r.resource_id AND rj.state='leased' AND rj.lease_until>(floor(extract(epoch FROM clock_timestamp())*1000)::bigint))<$6)
ORDER BY COALESCE(u.turn,0),COALESCE(t.turn,0),j.due_at,j.responsibility_key LIMIT $4 FOR UPDATE OF j SKIP LOCKED
`

type OrchestratorFairCandidatesParams struct {
	TenantID   string
	OwnerID    string
	Kind       string
	Limit      int32
	TenantID_2 string
	TenantID_3 string
}

type OrchestratorFairCandidatesRow struct {
	TenantID          string
	OwnerID           string
	Kind              string
	ResponsibilityKey string
	JobID             string
	SourceRef         string
	State             string
	DueAt             int64
	WorkRevision      int64
	LeaseEpoch        int64
	LeaseUntil        int64
	HolderID          string
	WaitReason        string
	SubjectID         string
	TaskID            string
}

func (q *Queries) OrchestratorFairCandidates(ctx context.Context, arg OrchestratorFairCandidatesParams) ([]OrchestratorFairCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorFairCandidates,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.Limit,
		arg.TenantID_2,
		arg.TenantID_3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorFairCandidatesRow
	for rows.Next() {
		var i OrchestratorFairCandidatesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.OwnerID,
			&i.Kind,
			&i.ResponsibilityKey,
			&i.JobID,
			&i.SourceRef,
			&i.State,
			&i.DueAt,
			&i.WorkRevision,
			&i.LeaseEpoch,
			&i.LeaseUntil,
			&i.HolderID,
			&i.WaitReason,
			&i.SubjectID,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorGateAdvance = `-- name: OrchestratorGateAdvance :exec
UPDATE orchestrator_gates SET revision=revision+1 WHERE tenant_id=$1 AND owner_id=$2 AND gate_key=$3
`

type OrchestratorGateAdvanceParams struct {
	TenantID string
	OwnerID  string
	GateKey  string
}

func (q *Queries) OrchestratorGateAdvance(ctx context.Context, arg OrchestratorGateAdvanceParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorGateAdvance, arg.TenantID, arg.OwnerID, arg.GateKey)
	return err
}

const OrchestratorGateCreate = `-- name: OrchestratorGateCreate :exec
INSERT INTO orchestrator_gates(tenant_id,owner_id,gate_key,revision) VALUES($1,$2,$3,1) ON CONFLICT DO NOTHING
`

type OrchestratorGateCreateParams struct {
	TenantID string
	OwnerID  string
	GateKey  string
}

func (q *Queries) OrchestratorGateCreate(ctx context.Context, arg OrchestratorGateCreateParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorGateCreate, arg.TenantID, arg.OwnerID, arg.GateKey)
	return err
}

const OrchestratorGetReceiver = `-- name: OrchestratorGetReceiver :one
SELECT data FROM orchestrator_receivers WHERE tenant_id=$1 AND owner_id=$2 AND allocation_id=$3
`

type OrchestratorGetReceiverParams struct {
	TenantID     string
	OwnerID      string
	AllocationID string
}

func (q *Queries) OrchestratorGetReceiver(ctx context.Context, arg OrchestratorGetReceiverParams) (string, error) {
	row := q.db.QueryRowContext(ctx, OrchestratorGetReceiver, arg.TenantID, arg.OwnerID, arg.AllocationID)
	var data string
	err := row.Scan(&data)
	return data, err
}

const OrchestratorGetRecord = `-- name: OrchestratorGetRecord :one
SELECT kind,id,task_id,revision,state,current_key,immutable,data FROM orchestrator_records WHERE tenant_id=$1 AND owner_id=$2 AND kind=$3 AND id=$4
`

type OrchestratorGetRecordParams struct {
	TenantID string
	OwnerID  string
	Kind     string
	ID       string
}

type OrchestratorGetRecordRow struct {
	Kind       string
	ID         string
	TaskID     string
	Revision   int64
	State      string
	CurrentKey string
	Immutable  bool
	Data       string
}

func (q *Queries) OrchestratorGetRecord(ctx context.Context, arg OrchestratorGetRecordParams) (OrchestratorGetRecordRow, error) {
	row := q.db.QueryRowContext(ctx, OrchestratorGetRecord,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.ID,
	)
	var i OrchestratorGetRecordRow
	err := row.Scan(
		&i.Kind,
		&i.ID,
		&i.TaskID,
		&i.Revision,
		&i.State,
		&i.CurrentKey,
		&i.Immutable,
		&i.Data,
	)
	return i, err
}

const OrchestratorGetRecords = `-- name: OrchestratorGetRecords :many
SELECT kind,id,task_id,revision,state,current_key,immutable,data FROM orchestrator_records WHERE tenant_id=$1 AND owner_id=$2 AND kind=$3 AND id IN (SELECT jsonb_array_elements_text($4::jsonb)) ORDER BY id LIMIT 101
`

type OrchestratorGetRecordsParams struct {
	TenantID string
	OwnerID  string
	Kind     string
	Column4  json.RawMessage
}

type OrchestratorGetRecordsRow struct {
	Kind       string
	ID         string
	TaskID     string
	Revision   int64
	State      string
	CurrentKey string
	Immutable  bool
	Data       string
}

func (q *Queries) OrchestratorGetRecords(ctx context.Context, arg OrchestratorGetRecordsParams) ([]OrchestratorGetRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorGetRecords,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorGetRecordsRow
	for rows.Next() {
		var i OrchestratorGetRecordsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.TaskID,
			&i.Revision,
			&i.State,
			&i.CurrentKey,
			&i.Immutable,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorGetTask = `-- name: OrchestratorGetTask :one
SELECT data FROM orchestrator_tasks WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3
`

type OrchestratorGetTaskParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
}

func (q *Queries) OrchestratorGetTask(ctx context.Context, arg OrchestratorGetTaskParams) (string, error) {
	row := q.db.QueryRowContext(ctx, OrchestratorGetTask, arg.TenantID, arg.OwnerID, arg.TaskID)
	var data string
	err := row.Scan(&data)
	return data, err
}

const OrchestratorList = `-- name: OrchestratorList :many
SELECT data FROM orchestrator_tasks WHERE tenant_id=$1 AND owner_id=$2 AND created_at<=$3
 AND (created_at<$4 OR (created_at=$4 AND task_id>$5))
ORDER BY created_at DESC,task_id LIMIT $6
`

type OrchestratorListParams struct {
	TenantID    string
	OwnerID     string
	CreatedAt   int64
	CreatedAt_2 int64
	TaskID      string
	Limit       int32
}

func (q *Queries) OrchestratorList(ctx context.Context, arg OrchestratorListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorList,
		arg.TenantID,
		arg.OwnerID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.TaskID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorLockBalances = `-- name: OrchestratorLockBalances :many
SELECT unit,limit_value,spent,reserved FROM orchestrator_balances WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3 ORDER BY unit LIMIT 101 FOR UPDATE
`

type OrchestratorLockBalancesParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
}

type OrchestratorLockBalancesRow struct {
	Unit       string
	LimitValue string
	Spent      string
	Reserved   string
}

func (q *Queries) OrchestratorLockBalances(ctx context.Context, arg OrchestratorLockBalancesParams) ([]OrchestratorLockBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorLockBalances, arg.TenantID, arg.OwnerID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorLockBalancesRow
	for rows.Next() {
		var i OrchestratorLockBalancesRow
		if err := rows.Scan(
			&i.Unit,
			&i.LimitValue,
			&i.Spent,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorLockCapacity = `-- name: OrchestratorLockCapacity :one
SELECT active_count FROM orchestrator_user_capacity WHERE tenant_id=$1 AND owner_id=$2 AND subject_id=$3 FOR UPDATE
`

type OrchestratorLockCapacityParams struct {
	TenantID  string
	OwnerID   string
	SubjectID string
}

func (q *Queries) OrchestratorLockCapacity(ctx context.Context, arg OrchestratorLockCapacityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, OrchestratorLockCapacity, arg.TenantID, arg.OwnerID, arg.SubjectID)
	var active_count int64
	err := row.Scan(&active_count)
	return active_count, err
}

const OrchestratorLockGate = `-- name: OrchestratorLockGate :one
SELECT revision FROM orchestrator_gates WHERE tenant_id=$1 AND owner_id=$2 AND gate_key=$3 FOR UPDATE
`

type OrchestratorLockGateParams struct {
	TenantID string
	OwnerID  string
	GateKey  string
}

func (q *Queries) OrchestratorLockGate(ctx context.Context, arg OrchestratorLockGateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, OrchestratorLockGate, arg.TenantID, arg.OwnerID, arg.GateKey)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const OrchestratorLockTask = `-- name: OrchestratorLockTask :one
SELECT data FROM orchestrator_tasks WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3 FOR UPDATE
`

type OrchestratorLockTaskParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
}

func (q *Queries) OrchestratorLockTask(ctx context.Context, arg OrchestratorLockTaskParams) (string, error) {
	row := q.db.QueryRowContext(ctx, OrchestratorLockTask, arg.TenantID, arg.OwnerID, arg.TaskID)
	var data string
	err := row.Scan(&data)
	return data, err
}

const OrchestratorOpenRecords = `-- name: OrchestratorOpenRecords :many
SELECT kind,id,task_id,revision,state,current_key,immutable,data FROM orchestrator_records
WHERE tenant_id=$1 AND owner_id=$2 AND kind=$3 AND state='open' AND id>$4 ORDER BY id LIMIT $5
`

type OrchestratorOpenRecordsParams struct {
	TenantID string
	OwnerID  string
	Kind     string
	ID       string
	Limit    int32
}

type OrchestratorOpenRecordsRow struct {
	Kind       string
	ID         string
	TaskID     string
	Revision   int64
	State      string
	CurrentKey string
	Immutable  bool
	Data       string
}

func (q *Queries) OrchestratorOpenRecords(ctx context.Context, arg OrchestratorOpenRecordsParams) ([]OrchestratorOpenRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorOpenRecords,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorOpenRecordsRow
	for rows.Next() {
		var i OrchestratorOpenRecordsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.TaskID,
			&i.Revision,
			&i.State,
			&i.CurrentKey,
			&i.Immutable,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorOpenTaskRecords = `-- name: OrchestratorOpenTaskRecords :many
SELECT kind,id,task_id,revision,state,current_key,immutable,data FROM orchestrator_records WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3 AND kind=$4 AND state='open' ORDER BY id LIMIT $5
`

type OrchestratorOpenTaskRecordsParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
	Kind     string
	Limit    int32
}

type OrchestratorOpenTaskRecordsRow struct {
	Kind       string
	ID         string
	TaskID     string
	Revision   int64
	State      string
	CurrentKey string
	Immutable  bool
	Data       string
}

func (q *Queries) OrchestratorOpenTaskRecords(ctx context.Context, arg OrchestratorOpenTaskRecordsParams) ([]OrchestratorOpenTaskRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorOpenTaskRecords,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Kind,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorOpenTaskRecordsRow
	for rows.Next() {
		var i OrchestratorOpenTaskRecordsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.TaskID,
			&i.Revision,
			&i.State,
			&i.CurrentKey,
			&i.Immutable,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorReadGate = `-- name: OrchestratorReadGate :one
SELECT revision FROM orchestrator_gates WHERE tenant_id=$1 AND owner_id=$2 AND gate_key=$3 FOR SHARE
`

type OrchestratorReadGateParams struct {
	TenantID string
	OwnerID  string
	GateKey  string
}

func (q *Queries) OrchestratorReadGate(ctx context.Context, arg OrchestratorReadGateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, OrchestratorReadGate, arg.TenantID, arg.OwnerID, arg.GateKey)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const OrchestratorRecords = `-- name: OrchestratorRecords :many
SELECT kind,id,task_id,revision,state,current_key,immutable,data FROM orchestrator_records
WHERE tenant_id=$1 AND owner_id=$2 AND task_id=$3 AND kind=$4 AND id>$5
 AND ($6='' OR state=$6) AND ($7='' OR current_key=$7 OR ($7='@current' AND current_key<>''))
ORDER BY id LIMIT $8
`

type OrchestratorRecordsParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
	Kind     string
	ID       string
	Column6  interface{}
	Column7  interface{}
	Limit    int32
}

type OrchestratorRecordsRow struct {
	Kind       string
	ID         string
	TaskID     string
	Revision   int64
	State      string
	CurrentKey string
	Immutable  bool
	Data       string
}

func (q *Queries) OrchestratorRecords(ctx context.Context, arg OrchestratorRecordsParams) ([]OrchestratorRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorRecords,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Kind,
		arg.ID,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestratorRecordsRow
	for rows.Next() {
		var i OrchestratorRecordsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.TaskID,
			&i.Revision,
			&i.State,
			&i.CurrentKey,
			&i.Immutable,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorRecovery = `-- name: OrchestratorRecovery :many
WITH ids AS (
 SELECT active.task_id FROM (SELECT t.task_id FROM orchestrator_tasks t WHERE t.tenant_id=$1 AND t.owner_id=$2 AND t.status='active' AND t.task_id>$3 ORDER BY t.task_id LIMIT $4) active
 UNION
 SELECT unresolved.task_id FROM (SELECT DISTINCT r.task_id FROM orchestrator_records r WHERE r.tenant_id=$1 AND r.owner_id=$2 AND r.state='open' AND r.kind IN ('reservation','control','intent','delegation','extraction') AND r.task_id>$3 ORDER BY r.task_id LIMIT $4) unresolved
), page AS (SELECT ids.task_id FROM ids ORDER BY ids.task_id LIMIT $4)
SELECT t.data FROM page p JOIN orchestrator_tasks t ON t.tenant_id=$1 AND t.owner_id=$2 AND t.task_id=p.task_id ORDER BY t.task_id
`

type OrchestratorRecoveryParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
	Limit    int32
}

func (q *Queries) OrchestratorRecovery(ctx context.Context, arg OrchestratorRecoveryParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorRecovery,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const OrchestratorSaveBalance = `-- name: OrchestratorSaveBalance :exec
INSERT INTO orchestrator_balances(tenant_id,owner_id,task_id,unit,limit_value,spent,reserved) VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(tenant_id,owner_id,task_id,unit) DO UPDATE SET limit_value=excluded.limit_value,spent=excluded.spent,reserved=excluded.reserved
`

type OrchestratorSaveBalanceParams struct {
	TenantID   string
	OwnerID    string
	TaskID     string
	Unit       string
	LimitValue string
	Spent      string
	Reserved   string
}

func (q *Queries) OrchestratorSaveBalance(ctx context.Context, arg OrchestratorSaveBalanceParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorSaveBalance,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Unit,
		arg.LimitValue,
		arg.Spent,
		arg.Reserved,
	)
	return err
}

const OrchestratorSaveBalances = `-- name: OrchestratorSaveBalances :exec
INSERT INTO orchestrator_balances(tenant_id,owner_id,task_id,unit,limit_value,spent,reserved) SELECT $1,$2,$3,value->>'unit',value#>>'{limit,amount}',value#>>'{spent,amount}',value#>>'{reserved,amount}' FROM jsonb_array_elements($4::jsonb)
ON CONFLICT(tenant_id,owner_id,task_id,unit) DO UPDATE SET limit_value=excluded.limit_value,spent=excluded.spent,reserved=excluded.reserved
`

type OrchestratorSaveBalancesParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
	Column4  json.RawMessage
}

func (q *Queries) OrchestratorSaveBalances(ctx context.Context, arg OrchestratorSaveBalancesParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorSaveBalances,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Column4,
	)
	return err
}

const OrchestratorSaveReceiver = `-- name: OrchestratorSaveReceiver :exec
INSERT INTO orchestrator_receivers(tenant_id,owner_id,allocation_id,data) VALUES($1,$2,$3,$4)
ON CONFLICT(tenant_id,owner_id,allocation_id) DO UPDATE SET data=excluded.data
`

type OrchestratorSaveReceiverParams struct {
	TenantID     string
	OwnerID      string
	AllocationID string
	Data         string
}

func (q *Queries) OrchestratorSaveReceiver(ctx context.Context, arg OrchestratorSaveReceiverParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorSaveReceiver,
		arg.TenantID,
		arg.OwnerID,
		arg.AllocationID,
		arg.Data,
	)
	return err
}

const OrchestratorSaveRecord = `-- name: OrchestratorSaveRecord :execrows
INSERT INTO orchestrator_records(tenant_id,owner_id,kind,id,task_id,revision,state,current_key,immutable,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT(tenant_id,owner_id,kind,id) DO UPDATE SET revision=excluded.revision,state=excluded.state,current_key=excluded.current_key,data=excluded.data
WHERE orchestrator_records.task_id=excluded.task_id AND orchestrator_records.immutable=excluded.immutable
 AND orchestrator_records.revision<=excluded.revision
 AND (orchestrator_records.immutable=FALSE OR orchestrator_records.data=excluded.data)
`

type OrchestratorSaveRecordParams struct {
	TenantID   string
	OwnerID    string
	Kind       string
	ID         string
	TaskID     string
	Revision   int64
	State      string
	CurrentKey string
	Immutable  bool
	Data       string
}

func (q *Queries) OrchestratorSaveRecord(ctx context.Context, arg OrchestratorSaveRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, OrchestratorSaveRecord,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.ID,
		arg.TaskID,
		arg.Revision,
		arg.State,
		arg.CurrentKey,
		arg.Immutable,
		arg.Data,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const OrchestratorSaveRecords = `-- name: OrchestratorSaveRecords :execrows
INSERT INTO orchestrator_records(tenant_id,owner_id,kind,id,task_id,revision,state,current_key,immutable,data)
SELECT $1,$2,x->>'Kind',x->>'ID',x->>'TaskID',(x->>'Revision')::bigint,x->>'State',x->>'CurrentKey',(x->>'Immutable')::boolean,x->'Data' FROM jsonb_array_elements($3::jsonb) AS x WHERE true
ON CONFLICT(tenant_id,owner_id,kind,id) DO UPDATE SET revision=excluded.revision,state=excluded.state,current_key=excluded.current_key,data=excluded.data
WHERE orchestrator_records.task_id=excluded.task_id AND orchestrator_records.immutable=excluded.immutable AND orchestrator_records.revision<=excluded.revision AND (orchestrator_records.immutable=FALSE OR orchestrator_records.data=excluded.data)
`

type OrchestratorSaveRecordsParams struct {
	TenantID string
	OwnerID  string
	Column3  json.RawMessage
}

func (q *Queries) OrchestratorSaveRecords(ctx context.Context, arg OrchestratorSaveRecordsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, OrchestratorSaveRecords, arg.TenantID, arg.OwnerID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const OrchestratorSaveRoute = `-- name: OrchestratorSaveRoute :exec
INSERT INTO orchestrator_work_routes(tenant_id,owner_id,kind,responsibility_key,subject_id,task_id,provider_id,resource_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING
`

type OrchestratorSaveRouteParams struct {
	TenantID          string
	OwnerID           string
	Kind              string
	ResponsibilityKey string
	SubjectID         string
	TaskID            string
	ProviderID        string
	ResourceID        string
}

func (q *Queries) OrchestratorSaveRoute(ctx context.Context, arg OrchestratorSaveRouteParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorSaveRoute,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.ResponsibilityKey,
		arg.SubjectID,
		arg.TaskID,
		arg.ProviderID,
		arg.ResourceID,
	)
	return err
}

const OrchestratorSaveRoutes = `-- name: OrchestratorSaveRoutes :execrows
INSERT INTO orchestrator_work_routes(tenant_id,owner_id,kind,responsibility_key,subject_id,task_id,provider_id,resource_id)
SELECT $1,$2,x->>'Kind',x->>'Responsibility',x->>'SubjectID',x->>'TaskID',x->>'ProviderID',x->>'ResourceID' FROM jsonb_array_elements($3::jsonb) AS x WHERE true
ON CONFLICT(tenant_id,owner_id,kind,responsibility_key) DO UPDATE SET task_id=excluded.task_id
WHERE orchestrator_work_routes.subject_id=excluded.subject_id AND orchestrator_work_routes.task_id=excluded.task_id AND orchestrator_work_routes.provider_id=excluded.provider_id AND orchestrator_work_routes.resource_id=excluded.resource_id
`

type OrchestratorSaveRoutesParams struct {
	TenantID string
	OwnerID  string
	Column3  json.RawMessage
}

func (q *Queries) OrchestratorSaveRoutes(ctx context.Context, arg OrchestratorSaveRoutesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, OrchestratorSaveRoutes, arg.TenantID, arg.OwnerID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const OrchestratorSaveTask = `-- name: OrchestratorSaveTask :execrows
INSERT INTO orchestrator_tasks(tenant_id,owner_id,task_id,subject_id,parent_task_id,depth,created_at,revision,status,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT(tenant_id,owner_id,task_id) DO UPDATE SET revision=excluded.revision,status=excluded.status,data=excluded.data
WHERE orchestrator_tasks.subject_id=excluded.subject_id AND orchestrator_tasks.parent_task_id=excluded.parent_task_id AND orchestrator_tasks.depth=excluded.depth AND orchestrator_tasks.created_at=excluded.created_at AND orchestrator_tasks.revision<excluded.revision
`

type OrchestratorSaveTaskParams struct {
	TenantID     string
	OwnerID      string
	TaskID       string
	SubjectID    string
	ParentTaskID string
	Depth        int64
	CreatedAt    int64
	Revision     int64
	Status       string
	Data         string
}

func (q *Queries) OrchestratorSaveTask(ctx context.Context, arg OrchestratorSaveTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, OrchestratorSaveTask,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.SubjectID,
		arg.ParentTaskID,
		arg.Depth,
		arg.CreatedAt,
		arg.Revision,
		arg.Status,
		arg.Data,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const OrchestratorScheduleAdvance = `-- name: OrchestratorScheduleAdvance :exec
UPDATE orchestrator_scheduler SET turn=turn+1 WHERE tenant_id=$1 AND owner_id=$2 AND kind=$3
`

type OrchestratorScheduleAdvanceParams struct {
	TenantID string
	OwnerID  string
	Kind     string
}

func (q *Queries) OrchestratorScheduleAdvance(ctx context.Context, arg OrchestratorScheduleAdvanceParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorScheduleAdvance, arg.TenantID, arg.OwnerID, arg.Kind)
	return err
}

const OrchestratorScheduleCreate = `-- name: OrchestratorScheduleCreate :exec
INSERT INTO orchestrator_scheduler(tenant_id,owner_id,kind,turn) VALUES($1,$2,$3,0) ON CONFLICT DO NOTHING
`

type OrchestratorScheduleCreateParams struct {
	TenantID string
	OwnerID  string
	Kind     string
}

func (q *Queries) OrchestratorScheduleCreate(ctx context.Context, arg OrchestratorScheduleCreateParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorScheduleCreate, arg.TenantID, arg.OwnerID, arg.Kind)
	return err
}

const OrchestratorScheduleLock = `-- name: OrchestratorScheduleLock :one
SELECT turn FROM orchestrator_scheduler WHERE tenant_id=$1 AND owner_id=$2 AND kind=$3 FOR UPDATE
`

type OrchestratorScheduleLockParams struct {
	TenantID string
	OwnerID  string
	Kind     string
}

func (q *Queries) OrchestratorScheduleLock(ctx context.Context, arg OrchestratorScheduleLockParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, OrchestratorScheduleLock, arg.TenantID, arg.OwnerID, arg.Kind)
	var turn int64
	err := row.Scan(&turn)
	return turn, err
}

const OrchestratorScheduleTurns = `-- name: OrchestratorScheduleTurns :exec
INSERT INTO orchestrator_schedule_turns(tenant_id,owner_id,kind,dimension,entity_id,turn)
VALUES($1,$2,$3,'user',$4,$6),($1,$2,$3,'task',$5,$6)
ON CONFLICT(tenant_id,owner_id,kind,dimension,entity_id) DO UPDATE SET turn=excluded.turn
`

type OrchestratorScheduleTurnsParams struct {
	TenantID   string
	OwnerID    string
	Kind       string
	EntityID   string
	EntityID_2 string
	Turn       int64
}

func (q *Queries) OrchestratorScheduleTurns(ctx context.Context, arg OrchestratorScheduleTurnsParams) error {
	_, err := q.db.ExecContext(ctx, OrchestratorScheduleTurns,
		arg.TenantID,
		arg.OwnerID,
		arg.Kind,
		arg.EntityID,
		arg.EntityID_2,
		arg.Turn,
	)
	return err
}

const OrchestratorTree = `-- name: OrchestratorTree :many
WITH RECURSIVE tree AS (
 SELECT origin.task_id,origin.parent_task_id,origin.depth,origin.data FROM orchestrator_tasks origin WHERE origin.tenant_id=$1 AND origin.owner_id=$2 AND origin.task_id=$3
 UNION ALL
 SELECT t.task_id,t.parent_task_id,t.depth,t.data FROM orchestrator_tasks t JOIN tree p ON t.parent_task_id=p.task_id WHERE t.tenant_id=$1 AND t.owner_id=$2 AND t.status='active'
) SELECT data FROM tree ORDER BY depth,task_id LIMIT $4
`

type OrchestratorTreeParams struct {
	TenantID string
	OwnerID  string
	TaskID   string
	Limit    int32
}

func (q *Queries) OrchestratorTree(ctx context.Context, arg OrchestratorTreeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, OrchestratorTree,
		arg.TenantID,
		arg.OwnerID,
		arg.TaskID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
