// Code generated by scripts/generate.mjs v1.0.0 from contract/schema/1.0.0/values.json; DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/ruipengliu/lerna/contract"
)

func run(name string, data []byte) ([]byte, error) {
	if name == "CommandInput" {
		value, err := contract.DecodeCommand(data)
		if err != nil {
			return nil, err
		}
		return contract.Encode(value)
	}
	switch name {
	case "ID":
		return roundtrip[contract.ID](data)
	case "Revision":
		return roundtrip[contract.Revision](data)
	case "Time":
		return roundtrip[contract.Time](data)
	case "Kind":
		return roundtrip[contract.Kind](data)
	case "OwnerRef":
		return roundtrip[contract.OwnerRef](data)
	case "ObjectRef":
		return roundtrip[contract.ObjectRef](data)
	case "ContentRef":
		return roundtrip[contract.ContentRef](data)
	case "Amount":
		return roundtrip[contract.Amount](data)
	case "Gap":
		return roundtrip[contract.Gap](data)
	case "ReadScope":
		return roundtrip[contract.ReadScope](data)
	case "CollectionView":
		return roundtrip[contract.CollectionView](data)
	case "ErrorCode":
		return roundtrip[contract.ErrorCode](data)
	case "PublicError":
		return roundtrip[contract.PublicError](data)
	case "MethodName":
		return roundtrip[contract.MethodName](data)
	case "ProfileName":
		return roundtrip[contract.ProfileName](data)
	case "ContractVersion":
		return roundtrip[contract.ContractVersion](data)
	case "TraceContext":
		return roundtrip[contract.TraceContext](data)
	case "CommandPayload":
		return roundtrip[contract.CommandPayload](data)
	case "CommandEnvelope":
		return roundtrip[contract.CommandEnvelope](data)
	case "CommandRef":
		return roundtrip[contract.CommandRef](data)
	case "CommandGetPayload":
		return roundtrip[contract.CommandGetPayload](data)
	case "CommandGetRequest":
		return roundtrip[contract.CommandGetRequest](data)
	case "CommandTarget":
		return roundtrip[contract.CommandTarget](data)
	default:
		return nil, fmt.Errorf("unknown value schema %q", name)
	}
}
