// Code generated by scripts/generate.mjs v1.0.0 from contract/schema/1.2.0/values.json; DO NOT EDIT.
package main

import (
	"fmt"
	contract "github.com/ruipengliu/lerna/contract/v1_2"
)

func run(name string, data []byte) ([]byte, error) {
	if name == "CommandInput" {
		value, err := contract.DecodeCommand(data)
		if err != nil {
			return nil, err
		}
		return contract.Encode(value)
	}
	switch name {
	case "ID":
		return roundtrip[contract.ID](data)
	case "Revision":
		return roundtrip[contract.Revision](data)
	case "Time":
		return roundtrip[contract.Time](data)
	case "Kind":
		return roundtrip[contract.Kind](data)
	case "OwnerRef":
		return roundtrip[contract.OwnerRef](data)
	case "ObjectRef":
		return roundtrip[contract.ObjectRef](data)
	case "ContentRef":
		return roundtrip[contract.ContentRef](data)
	case "ErrorCode":
		return roundtrip[contract.ErrorCode](data)
	case "PublicError":
		return roundtrip[contract.PublicError](data)
	case "MethodName":
		return roundtrip[contract.MethodName](data)
	case "ProfileName":
		return roundtrip[contract.ProfileName](data)
	case "ContractVersion":
		return roundtrip[contract.ContractVersion](data)
	case "TraceContext":
		return roundtrip[contract.TraceContext](data)
	case "CommandPayload":
		return roundtrip[contract.CommandPayload](data)
	case "CommandEnvelope":
		return roundtrip[contract.CommandEnvelope](data)
	case "CommandRef":
		return roundtrip[contract.CommandRef](data)
	case "CommandGetPayload":
		return roundtrip[contract.CommandGetPayload](data)
	case "CommandGetRequest":
		return roundtrip[contract.CommandGetRequest](data)
	case "CommandTarget":
		return roundtrip[contract.CommandTarget](data)
	case "CommandReceiptAccepted":
		return roundtrip[contract.CommandReceiptAccepted](data)
	case "CommandReceiptRejected":
		return roundtrip[contract.CommandReceiptRejected](data)
	case "CommandReceipt":
		return roundtrip[contract.CommandReceipt](data)
	case "CommandProgressNone":
		return roundtrip[contract.CommandProgressNone](data)
	case "CommandProgressUnavailable":
		return roundtrip[contract.CommandProgressUnavailable](data)
	case "CommandProgress":
		return roundtrip[contract.CommandProgress](data)
	case "CommandGetResponseFound":
		return roundtrip[contract.CommandGetResponseFound](data)
	case "CommandGetResponseNotFound":
		return roundtrip[contract.CommandGetResponseNotFound](data)
	case "CommandGetResponseGone":
		return roundtrip[contract.CommandGetResponseGone](data)
	case "CommandGetResponseUnavailable":
		return roundtrip[contract.CommandGetResponseUnavailable](data)
	case "CommandGetResponseRejected":
		return roundtrip[contract.CommandGetResponseRejected](data)
	case "CommandGetResponse":
		return roundtrip[contract.CommandGetResponse](data)
	case "TransportOutcomeReceived":
		return roundtrip[contract.TransportOutcomeReceived](data)
	case "TransportOutcomeCommitUnknown":
		return roundtrip[contract.TransportOutcomeCommitUnknown](data)
	case "TransportOutcome":
		return roundtrip[contract.TransportOutcome](data)
	case "DelegatedSubject":
		return roundtrip[contract.DelegatedSubject](data)
	case "SubjectBinding":
		return roundtrip[contract.SubjectBinding](data)
	case "SchemaDigest":
		return roundtrip[contract.SchemaDigest](data)
	case "MethodSupport":
		return roundtrip[contract.MethodSupport](data)
	case "NegotiationRequest":
		return roundtrip[contract.NegotiationRequest](data)
	case "Purpose":
		return roundtrip[contract.Purpose](data)
	case "ContentTarget":
		return roundtrip[contract.ContentTarget](data)
	case "ContentRange":
		return roundtrip[contract.ContentRange](data)
	case "ContentPutPayload":
		return roundtrip[contract.ContentPutPayload](data)
	case "ContentGetPayload":
		return roundtrip[contract.ContentGetPayload](data)
	case "ContentPutRequest":
		return roundtrip[contract.ContentPutRequest](data)
	case "ContentGetRequest":
		return roundtrip[contract.ContentGetRequest](data)
	case "CommandProgressContent":
		return roundtrip[contract.CommandProgressContent](data)
	case "ContentGetResponsePreparing":
		return roundtrip[contract.ContentGetResponsePreparing](data)
	case "ContentGetResponsePublished":
		return roundtrip[contract.ContentGetResponsePublished](data)
	case "ContentGetResponseFailed":
		return roundtrip[contract.ContentGetResponseFailed](data)
	case "ContentGetResponseGone":
		return roundtrip[contract.ContentGetResponseGone](data)
	case "ContentGetResponseUnavailable":
		return roundtrip[contract.ContentGetResponseUnavailable](data)
	case "ContentGetResponseNotFound":
		return roundtrip[contract.ContentGetResponseNotFound](data)
	case "ContentGetResponseRejected":
		return roundtrip[contract.ContentGetResponseRejected](data)
	case "ContentGetResponse":
		return roundtrip[contract.ContentGetResponse](data)
	default:
		return nil, fmt.Errorf("unknown value schema %q", name)
	}
}
