// Code generated by scripts/generate.mjs v1.0.0 from contract/schema/1.1.0/values.json; DO NOT EDIT.
package main

import (
	"fmt"
	contract "github.com/ruipengliu/lerna/contract/v1_1"
)

func run(name string, data []byte) ([]byte, error) {
	if name == "CommandInput" {
		value, err := contract.DecodeCommand(data)
		if err != nil {
			return nil, err
		}
		return contract.Encode(value)
	}
	if name == "DecideInput" {
		value, err := contract.DecodeDecide(data)
		if err != nil {
			return nil, err
		}
		return contract.Encode(value)
	}
	if name == "GetInput" {
		value, err := contract.DecodeGet(data)
		if err != nil {
			return nil, err
		}
		return contract.Encode(value)
	}
	if name == "CancelInput" {
		value, err := contract.DecodeCancel(data)
		if err != nil {
			return nil, err
		}
		return contract.Encode(value)
	}
	switch name {
	case "ID":
		return roundtrip[contract.ID](data)
	case "Revision":
		return roundtrip[contract.Revision](data)
	case "Time":
		return roundtrip[contract.Time](data)
	case "Kind":
		return roundtrip[contract.Kind](data)
	case "OwnerRef":
		return roundtrip[contract.OwnerRef](data)
	case "ObjectRef":
		return roundtrip[contract.ObjectRef](data)
	case "ContentRef":
		return roundtrip[contract.ContentRef](data)
	case "Amount":
		return roundtrip[contract.Amount](data)
	case "Gap":
		return roundtrip[contract.Gap](data)
	case "ReadScope":
		return roundtrip[contract.ReadScope](data)
	case "CollectionView":
		return roundtrip[contract.CollectionView](data)
	case "ErrorCode":
		return roundtrip[contract.ErrorCode](data)
	case "PublicError":
		return roundtrip[contract.PublicError](data)
	case "MethodName":
		return roundtrip[contract.MethodName](data)
	case "ProfileName":
		return roundtrip[contract.ProfileName](data)
	case "ContractVersion":
		return roundtrip[contract.ContractVersion](data)
	case "TraceContext":
		return roundtrip[contract.TraceContext](data)
	case "CommandPayload":
		return roundtrip[contract.CommandPayload](data)
	case "CommandEnvelope":
		return roundtrip[contract.CommandEnvelope](data)
	case "CommandRef":
		return roundtrip[contract.CommandRef](data)
	case "CommandGetPayload":
		return roundtrip[contract.CommandGetPayload](data)
	case "CommandGetRequest":
		return roundtrip[contract.CommandGetRequest](data)
	case "CommandTarget":
		return roundtrip[contract.CommandTarget](data)
	case "NextAction":
		return roundtrip[contract.NextAction](data)
	case "CommandReceiptAccepted":
		return roundtrip[contract.CommandReceiptAccepted](data)
	case "CommandReceiptApplied":
		return roundtrip[contract.CommandReceiptApplied](data)
	case "CommandReceiptRejected":
		return roundtrip[contract.CommandReceiptRejected](data)
	case "CommandReceipt":
		return roundtrip[contract.CommandReceipt](data)
	case "TaskObjectRef":
		return roundtrip[contract.TaskObjectRef](data)
	case "CommandProgressNone":
		return roundtrip[contract.CommandProgressNone](data)
	case "CommandProgressUnavailable":
		return roundtrip[contract.CommandProgressUnavailable](data)
	case "CommandProgressTask":
		return roundtrip[contract.CommandProgressTask](data)
	case "CommandProgress":
		return roundtrip[contract.CommandProgress](data)
	case "CommandGetResponseFound":
		return roundtrip[contract.CommandGetResponseFound](data)
	case "CommandGetResponseNotFound":
		return roundtrip[contract.CommandGetResponseNotFound](data)
	case "CommandGetResponseGone":
		return roundtrip[contract.CommandGetResponseGone](data)
	case "CommandGetResponseUnavailable":
		return roundtrip[contract.CommandGetResponseUnavailable](data)
	case "CommandGetResponseRejected":
		return roundtrip[contract.CommandGetResponseRejected](data)
	case "CommandGetResponse":
		return roundtrip[contract.CommandGetResponse](data)
	case "TransportOutcomeReceived":
		return roundtrip[contract.TransportOutcomeReceived](data)
	case "TransportOutcomeCommitUnknown":
		return roundtrip[contract.TransportOutcomeCommitUnknown](data)
	case "TransportOutcome":
		return roundtrip[contract.TransportOutcome](data)
	case "DelegatedSubject":
		return roundtrip[contract.DelegatedSubject](data)
	case "SubjectBinding":
		return roundtrip[contract.SubjectBinding](data)
	case "SchemaDigest":
		return roundtrip[contract.SchemaDigest](data)
	case "MethodSupport":
		return roundtrip[contract.MethodSupport](data)
	case "NegotiationRequest":
		return roundtrip[contract.NegotiationRequest](data)
	case "DecisionRef":
		return roundtrip[contract.DecisionRef](data)
	case "SnapshotRef":
		return roundtrip[contract.SnapshotRef](data)
	case "RequirementRef":
		return roundtrip[contract.RequirementRef](data)
	case "CapabilityRef":
		return roundtrip[contract.CapabilityRef](data)
	case "BindingRef":
		return roundtrip[contract.BindingRef](data)
	case "UseRef":
		return roundtrip[contract.UseRef](data)
	case "InstallLockRef":
		return roundtrip[contract.InstallLockRef](data)
	case "ComponentRef":
		return roundtrip[contract.ComponentRef](data)
	case "DecisionLimits":
		return roundtrip[contract.DecisionLimits](data)
	case "DecisionUsage":
		return roundtrip[contract.DecisionUsage](data)
	case "DecisionDecidePayload":
		return roundtrip[contract.DecisionDecidePayload](data)
	case "DecisionGetPayload":
		return roundtrip[contract.DecisionGetPayload](data)
	case "ControlBasis":
		return roundtrip[contract.ControlBasis](data)
	case "DecisionCancelPayload":
		return roundtrip[contract.DecisionCancelPayload](data)
	case "DecisionDecideRequest":
		return roundtrip[contract.DecisionDecideRequest](data)
	case "DecisionGetRequest":
		return roundtrip[contract.DecisionGetRequest](data)
	case "DecisionCancelRequest":
		return roundtrip[contract.DecisionCancelRequest](data)
	case "RequirementDelta":
		return roundtrip[contract.RequirementDelta](data)
	case "ProposalAction":
		return roundtrip[contract.ProposalAction](data)
	case "ProposalEvidence":
		return roundtrip[contract.ProposalEvidence](data)
	case "ProposalAdvanceNone":
		return roundtrip[contract.ProposalAdvanceNone](data)
	case "ProposalAdvanceActions":
		return roundtrip[contract.ProposalAdvanceActions](data)
	case "ProposalAdvanceInputRequest":
		return roundtrip[contract.ProposalAdvanceInputRequest](data)
	case "ProposalAdvanceCandidateResult":
		return roundtrip[contract.ProposalAdvanceCandidateResult](data)
	case "ProposalAdvanceCannotContinue":
		return roundtrip[contract.ProposalAdvanceCannotContinue](data)
	case "ProposalAdvance":
		return roundtrip[contract.ProposalAdvance](data)
	case "Proposal":
		return roundtrip[contract.Proposal](data)
	case "DecisionFailure":
		return roundtrip[contract.DecisionFailure](data)
	case "DecisionAccepted":
		return roundtrip[contract.DecisionAccepted](data)
	case "DecisionRunning":
		return roundtrip[contract.DecisionRunning](data)
	case "DecisionWaiting":
		return roundtrip[contract.DecisionWaiting](data)
	case "DecisionCompleted":
		return roundtrip[contract.DecisionCompleted](data)
	case "DecisionFailed":
		return roundtrip[contract.DecisionFailed](data)
	case "DecisionCancelled":
		return roundtrip[contract.DecisionCancelled](data)
	case "Decision":
		return roundtrip[contract.Decision](data)
	case "DecisionGetResponseFound":
		return roundtrip[contract.DecisionGetResponseFound](data)
	case "DecisionGetResponseResultUnavailable":
		return roundtrip[contract.DecisionGetResponseResultUnavailable](data)
	case "DecisionGetResponseUnavailable":
		return roundtrip[contract.DecisionGetResponseUnavailable](data)
	case "DecisionGetResponseRejected":
		return roundtrip[contract.DecisionGetResponseRejected](data)
	case "DecisionGetResponse":
		return roundtrip[contract.DecisionGetResponse](data)
	case "CommandProgressDecision":
		return roundtrip[contract.CommandProgressDecision](data)
	default:
		return nil, fmt.Errorf("unknown value schema %q", name)
	}
}
