// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: harness.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LogicalServiceId string                 `protobuf:"bytes,1,opt,name=logical_service_id,json=logicalServiceId,proto3" json:"logical_service_id,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*CallRequest_CommandJson
	//	*CallRequest_QueryJson
	//	*CallRequest_ReceiptLookupJson
	//	*CallRequest_ContentTransferJson
	Request       isCallRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_harness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetLogicalServiceId() string {
	if x != nil {
		return x.LogicalServiceId
	}
	return ""
}

func (x *CallRequest) GetRequest() isCallRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CallRequest) GetCommandJson() []byte {
	if x != nil {
		if x, ok := x.Request.(*CallRequest_CommandJson); ok {
			return x.CommandJson
		}
	}
	return nil
}

func (x *CallRequest) GetQueryJson() []byte {
	if x != nil {
		if x, ok := x.Request.(*CallRequest_QueryJson); ok {
			return x.QueryJson
		}
	}
	return nil
}

func (x *CallRequest) GetReceiptLookupJson() []byte {
	if x != nil {
		if x, ok := x.Request.(*CallRequest_ReceiptLookupJson); ok {
			return x.ReceiptLookupJson
		}
	}
	return nil
}

func (x *CallRequest) GetContentTransferJson() []byte {
	if x != nil {
		if x, ok := x.Request.(*CallRequest_ContentTransferJson); ok {
			return x.ContentTransferJson
		}
	}
	return nil
}

type isCallRequest_Request interface {
	isCallRequest_Request()
}

type CallRequest_CommandJson struct {
	CommandJson []byte `protobuf:"bytes,2,opt,name=command_json,json=commandJson,proto3,oneof"`
}

type CallRequest_QueryJson struct {
	QueryJson []byte `protobuf:"bytes,3,opt,name=query_json,json=queryJson,proto3,oneof"`
}

type CallRequest_ReceiptLookupJson struct {
	ReceiptLookupJson []byte `protobuf:"bytes,4,opt,name=receipt_lookup_json,json=receiptLookupJson,proto3,oneof"`
}

type CallRequest_ContentTransferJson struct {
	ContentTransferJson []byte `protobuf:"bytes,5,opt,name=content_transfer_json,json=contentTransferJson,proto3,oneof"`
}

func (*CallRequest_CommandJson) isCallRequest_Request() {}

func (*CallRequest_QueryJson) isCallRequest_Request() {}

func (*CallRequest_ReceiptLookupJson) isCallRequest_Request() {}

func (*CallRequest_ContentTransferJson) isCallRequest_Request() {}

type CallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CallResponse_ReceiptJson
	//	*CallResponse_QueryResultJson
	//	*CallResponse_ErrorJson
	//	*CallResponse_ContentTransferJson
	Result        isCallResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_harness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetResult() isCallResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CallResponse) GetReceiptJson() []byte {
	if x != nil {
		if x, ok := x.Result.(*CallResponse_ReceiptJson); ok {
			return x.ReceiptJson
		}
	}
	return nil
}

func (x *CallResponse) GetQueryResultJson() []byte {
	if x != nil {
		if x, ok := x.Result.(*CallResponse_QueryResultJson); ok {
			return x.QueryResultJson
		}
	}
	return nil
}

func (x *CallResponse) GetErrorJson() []byte {
	if x != nil {
		if x, ok := x.Result.(*CallResponse_ErrorJson); ok {
			return x.ErrorJson
		}
	}
	return nil
}

func (x *CallResponse) GetContentTransferJson() []byte {
	if x != nil {
		if x, ok := x.Result.(*CallResponse_ContentTransferJson); ok {
			return x.ContentTransferJson
		}
	}
	return nil
}

type isCallResponse_Result interface {
	isCallResponse_Result()
}

type CallResponse_ReceiptJson struct {
	ReceiptJson []byte `protobuf:"bytes,1,opt,name=receipt_json,json=receiptJson,proto3,oneof"`
}

type CallResponse_QueryResultJson struct {
	QueryResultJson []byte `protobuf:"bytes,2,opt,name=query_result_json,json=queryResultJson,proto3,oneof"`
}

type CallResponse_ErrorJson struct {
	ErrorJson []byte `protobuf:"bytes,3,opt,name=error_json,json=errorJson,proto3,oneof"`
}

type CallResponse_ContentTransferJson struct {
	ContentTransferJson []byte `protobuf:"bytes,4,opt,name=content_transfer_json,json=contentTransferJson,proto3,oneof"`
}

func (*CallResponse_ReceiptJson) isCallResponse_Result() {}

func (*CallResponse_QueryResultJson) isCallResponse_Result() {}

func (*CallResponse_ErrorJson) isCallResponse_Result() {}

func (*CallResponse_ContentTransferJson) isCallResponse_Result() {}

type ChannelFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BindingId       string                 `protobuf:"bytes,1,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	BindingRevision uint64                 `protobuf:"varint,2,opt,name=binding_revision,json=bindingRevision,proto3" json:"binding_revision,omitempty"`
	FrameJson       []byte                 `protobuf:"bytes,3,opt,name=frame_json,json=frameJson,proto3" json:"frame_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelFrame) Reset() {
	*x = ChannelFrame{}
	mi := &file_harness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelFrame) ProtoMessage() {}

func (x *ChannelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelFrame.ProtoReflect.Descriptor instead.
func (*ChannelFrame) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelFrame) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *ChannelFrame) GetBindingRevision() uint64 {
	if x != nil {
		return x.BindingRevision
	}
	return 0
}

func (x *ChannelFrame) GetFrameJson() []byte {
	if x != nil {
		return x.FrameJson
	}
	return nil
}

var File_harness_proto protoreflect.FileDescriptor

const file_harness_proto_rawDesc = "" +
	"\n" +
	"\rharness.proto\x12\x0eharness.rpc.v1\"\xf4\x01\n" +
	"\vCallRequest\x12,\n" +
	"\x12logical_service_id\x18\x01 \x01(\tR\x10logicalServiceId\x12#\n" +
	"\fcommand_json\x18\x02 \x01(\fH\x00R\vcommandJson\x12\x1f\n" +
	"\n" +
	"query_json\x18\x03 \x01(\fH\x00R\tqueryJson\x120\n" +
	"\x13receipt_lookup_json\x18\x04 \x01(\fH\x00R\x11receiptLookupJson\x124\n" +
	"\x15content_transfer_json\x18\x05 \x01(\fH\x00R\x13contentTransferJsonB\t\n" +
	"\arequest\"\xc2\x01\n" +
	"\fCallResponse\x12#\n" +
	"\freceipt_json\x18\x01 \x01(\fH\x00R\vreceiptJson\x12,\n" +
	"\x11query_result_json\x18\x02 \x01(\fH\x00R\x0fqueryResultJson\x12\x1f\n" +
	"\n" +
	"error_json\x18\x03 \x01(\fH\x00R\terrorJson\x124\n" +
	"\x15content_transfer_json\x18\x04 \x01(\fH\x00R\x13contentTransferJsonB\b\n" +
	"\x06result\"w\n" +
	"\fChannelFrame\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x01 \x01(\tR\tbindingId\x12)\n" +
	"\x10binding_revision\x18\x02 \x01(\x04R\x0fbindingRevision\x12\x1d\n" +
	"\n" +
	"frame_json\x18\x03 \x01(\fR\tframeJson2\xa6\x01\n" +
	"\x0eHarnessService\x12A\n" +
	"\x04Call\x12\x1b.harness.rpc.v1.CallRequest\x1a\x1c.harness.rpc.v1.CallResponse\x12Q\n" +
	"\x0fEndpointChannel\x12\x1c.harness.rpc.v1.ChannelFrame\x1a\x1c.harness.rpc.v1.ChannelFrame(\x010\x01b\x06proto3"

var (
	file_harness_proto_rawDescOnce sync.Once
	file_harness_proto_rawDescData []byte
)

func file_harness_proto_rawDescGZIP() []byte {
	file_harness_proto_rawDescOnce.Do(func() {
		file_harness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_harness_proto_rawDesc), len(file_harness_proto_rawDesc)))
	})
	return file_harness_proto_rawDescData
}

var file_harness_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_harness_proto_goTypes = []any{
	(*CallRequest)(nil),  // 0: harness.rpc.v1.CallRequest
	(*CallResponse)(nil), // 1: harness.rpc.v1.CallResponse
	(*ChannelFrame)(nil), // 2: harness.rpc.v1.ChannelFrame
}
var file_harness_proto_depIdxs = []int32{
	0, // 0: harness.rpc.v1.HarnessService.Call:input_type -> harness.rpc.v1.CallRequest
	2, // 1: harness.rpc.v1.HarnessService.EndpointChannel:input_type -> harness.rpc.v1.ChannelFrame
	1, // 2: harness.rpc.v1.HarnessService.Call:output_type -> harness.rpc.v1.CallResponse
	2, // 3: harness.rpc.v1.HarnessService.EndpointChannel:output_type -> harness.rpc.v1.ChannelFrame
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_harness_proto_init() }
func file_harness_proto_init() {
	if File_harness_proto != nil {
		return
	}
	file_harness_proto_msgTypes[0].OneofWrappers = []any{
		(*CallRequest_CommandJson)(nil),
		(*CallRequest_QueryJson)(nil),
		(*CallRequest_ReceiptLookupJson)(nil),
		(*CallRequest_ContentTransferJson)(nil),
	}
	file_harness_proto_msgTypes[1].OneofWrappers = []any{
		(*CallResponse_ReceiptJson)(nil),
		(*CallResponse_QueryResultJson)(nil),
		(*CallResponse_ErrorJson)(nil),
		(*CallResponse_ContentTransferJson)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_harness_proto_rawDesc), len(file_harness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harness_proto_goTypes,
		DependencyIndexes: file_harness_proto_depIdxs,
		MessageInfos:      file_harness_proto_msgTypes,
	}.Build()
	File_harness_proto = out.File
	file_harness_proto_goTypes = nil
	file_harness_proto_depIdxs = nil
}
