// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: harness.proto

package rpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HarnessService_Call_FullMethodName            = "/harness.rpc.v1.HarnessService/Call"
	HarnessService_EndpointChannel_FullMethodName = "/harness.rpc.v1.HarnessService/EndpointChannel"
)

// HarnessServiceClient is the client API for HarnessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Unpublished architecture-2026-10-data1 binding. JSON semantics live in the same profile.
type HarnessServiceClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	EndpointChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChannelFrame, ChannelFrame], error)
}

type harnessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHarnessServiceClient(cc grpc.ClientConnInterface) HarnessServiceClient {
	return &harnessServiceClient{cc}
}

func (c *harnessServiceClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, HarnessService_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessServiceClient) EndpointChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChannelFrame, ChannelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HarnessService_ServiceDesc.Streams[0], HarnessService_EndpointChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChannelFrame, ChannelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HarnessService_EndpointChannelClient = grpc.BidiStreamingClient[ChannelFrame, ChannelFrame]

// HarnessServiceServer is the server API for HarnessService service.
// All implementations must embed UnimplementedHarnessServiceServer
// for forward compatibility.
//
// Unpublished architecture-2026-10-data1 binding. JSON semantics live in the same profile.
type HarnessServiceServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	EndpointChannel(grpc.BidiStreamingServer[ChannelFrame, ChannelFrame]) error
	mustEmbedUnimplementedHarnessServiceServer()
}

// UnimplementedHarnessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHarnessServiceServer struct{}

func (UnimplementedHarnessServiceServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedHarnessServiceServer) EndpointChannel(grpc.BidiStreamingServer[ChannelFrame, ChannelFrame]) error {
	return status.Error(codes.Unimplemented, "method EndpointChannel not implemented")
}
func (UnimplementedHarnessServiceServer) mustEmbedUnimplementedHarnessServiceServer() {}
func (UnimplementedHarnessServiceServer) testEmbeddedByValue()                        {}

// UnsafeHarnessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HarnessServiceServer will
// result in compilation errors.
type UnsafeHarnessServiceServer interface {
	mustEmbedUnimplementedHarnessServiceServer()
}

func RegisterHarnessServiceServer(s grpc.ServiceRegistrar, srv HarnessServiceServer) {
	// If the following call panics, it indicates UnimplementedHarnessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HarnessService_ServiceDesc, srv)
}

func _HarnessService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessService_EndpointChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HarnessServiceServer).EndpointChannel(&grpc.GenericServerStream[ChannelFrame, ChannelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HarnessService_EndpointChannelServer = grpc.BidiStreamingServer[ChannelFrame, ChannelFrame]

// HarnessService_ServiceDesc is the grpc.ServiceDesc for HarnessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HarnessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "harness.rpc.v1.HarnessService",
	HandlerType: (*HarnessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _HarnessService_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EndpointChannel",
			Handler:       _HarnessService_EndpointChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "harness.proto",
}
