import copy,json
from pathlib import Path
root=Path('docs/architecture/contracts/schemas')
base=json.loads((root/'protocol.schema.json').read_text())['$defs']
registry=json.loads((root/'methods.json').read_text())['methods']
def ref(n):return {'$ref':'#/$defs/'+n}
def obj(p,optional=()):return {'type':'object','properties':p,'required':[k for k in p if k not in optional],'additionalProperties':False}
def arr(v,lo=0,hi=100):return {'type':'array','items':v,'minItems':lo,'maxItems':hi}
def enum(*v):return {'enum':list(v)}
def const(v):return {'const':v}
def text(n=4096):return {'type':'string','minLength':1,'maxLength':n}
def integer(lo=0,hi=None):return {'type':'integer','minimum':lo,**({'maximum':hi} if hi is not None else {})}
def nullable(v):return {'oneOf':[v,{'type':'null'}]}
ID=ref('Id');REV=ref('Revision');DIG=ref('Digest');CR=ref('ContentRef');OR=ref('ObjectRef');CP=ref('ComponentRef');AR=ref('AuthorizationRef');BOOL={'type':'boolean'};DT={'type':'string','format':'date-time','pattern':'Z$'}
defs={};methods={}
def add(n,v):defs[n]=v;return ref(n)
def method(name,inp,out,kind='query',target='owner_id',conditional=False,success='',extra=(),stages=None):
 pre= ''.join(x.title() for x in name.split('.'))
 defs[pre+'Input']=inp;defs[pre+'Output']=out
 errors=copy.deepcopy(registry['memory.create']['error_recovery'])
 for code in extra:errors[code]=['after_change','none'] if code not in ('cursor_expired','resnapshot_required') else ['after_change']
 methods[name]={'status':'frozen-draft','kind':kind,'input':pre+'Input','output':pre+'Output','target':target,'expected_revision':conditional,'stages':stages or (['applied','rejected'] if kind=='command' else []),'errors':list(errors),'success':success,'source':('interaction/README.md' if name.startswith('interaction.') else 'memory/README.md'),'error_recovery':errors}
# Immutable policy object: owner stores a version and applies intersection to actual source policies.
add('ContentPolicy',obj({'classification':enum('local_only','controlled_remote','replicated'),'allowed_locations':arr(ID,1),'allowed_recipients':arr(ID,1),'allowed_purposes':arr(text(256),1),'retention_until':DT,'offline_allowed':BOOL}))
add('ContentCommit',obj({'content_ref':CR,'policy_ref':OR,'control_revision':REV,'state':const('active')}))
add('ContentControl',obj({'content_ref':CR,'control_revision':REV,'state':enum('active','restricted','closed'),'policy_ref':OR,'cleanup_ref':OR},('cleanup_ref',)))
add('ContentCopy',obj({'copy_id':ID,'content_ref':CR,'holder_id':ID,'purpose':text(256),'recipient_id':ID,'retention_until':DT,'revision':REV,'use_stopped':BOOL,'physical_state':enum('pending','complete','residual','unknown'),'evidence_refs':arr(CR),'residual_reason':text()},('residual_reason',)))
add('CleanupHolder',obj({'holder_id':ID,'copy_id':ID,'use_stopped':BOOL,'physical_state':enum('pending','complete','residual','unknown'),'residual_reason':text(),'retry_after_ms':integer()},('residual_reason','retry_after_ms')))
add('CleanupReport',obj({'object_ref':OR,'closure_revision':REV,'holders':arr(ref('CleanupHolder')),'physical_state':enum('pending','complete','residual','unknown')}))
method('content.put',obj({'upload_id':ID,'content_ref':CR,'sources':arr(ref('SourceBinding')),'policy':ref('ContentPolicy')}),ref('ContentCommit'),'command','payload.content_ref.owner_id',success='提交已完整上传的不可变内容、策略与来源；正文不进入Command。',extra=('upload_incomplete','content_conflict','source_closed','source_unavailable'))
method('content.get',obj({'content_ref':CR,'copy_id':ID,'purpose':text(256),'recipient_id':ID,'usage_authorization_refs':arr(AR,1)}),obj({'content_ref':CR,'copy_id':ID,'control_revision':REV,'download_id':ID,'expires_at':DT,'range_supported':BOOL}),target='payload.content_ref.owner_id',success='已登记副本的当前获准有限下载定位；字节另走认证下载通道。',extra=('copy_not_registered','source_closed','source_unavailable'))
method('content.register_copy',obj({'copy_id':ID,'content_ref':CR,'holder_id':ID,'purpose':text(256),'recipient_id':ID,'retention_until':DT}),ref('ContentCopy'),'command','payload.content_ref.owner_id',success='交付前持久登记固定内容、持有者、用途与保留责任。',extra=('copy_conflict','source_closed','source_unavailable'))
method('content.release_copy',obj({'copy_id':ID,'content_ref':CR,'use_stopped':BOOL,'physical_state':enum('pending','complete','residual','unknown'),'evidence_refs':arr(CR),'residual_reason':text()},('residual_reason',)),ref('ContentCopy'),'command','payload.content_ref.owner_id',success='保存逐副本停止与物理清理事实；仍未知时保留责任。',extra=('copy_not_registered','copy_conflict'))
method('content.close',obj({'content_ref':CR,'mode':enum('restrict','close'),'reason':text(),'policy':ref('ContentPolicy')},('policy',)),ref('ContentControl'),'command','payload.content_ref.owner_id',True,'保存当前控制修订、最小关闭索引及传播清理责任。',('source_closed','policy_not_restriction'))
# Query sets bind their query id and cursor; results never disclose skipped identities.
add('MemoryQueryPage',obj({'query_id':ID,'owner_id':ID,'items':arr(ref('MemoryRecord'),0,200),'position':integer(),'scanned_count':integer(0,200),'skipped_count':integer(0,200),'next_cursor':text(),'exhausted':BOOL,'partial':BOOL,'changed':BOOL,'gaps':arr(text())},('next_cursor',)))
method('memory.query',obj({'query_id':ID,'owner_ids':arr(ID,1,16),'text_terms':arr(text(256),0,32),'types':arr(enum('fact','preference','inference','experience'),0,4),'scope':ref('Scope'),'purpose':text(256),'recipient_id':ID,'limit':integer(1,200),'cursor':text()},('cursor',)),ref('MemoryQueryPage'),success='固定有限候选集合，逐页复核当前状态/来源/用途，返回完整性与缺口。',extra=('cursor_expired','query_conflict','source_unavailable','source_closed'))
method('memory.list',obj({'query_id':ID,'types':arr(enum('fact','preference','inference','experience'),0,4),'states':arr(enum('active','needs_review','disabled','deleted'),0,4),'limit':integer(1,200),'cursor':text()},('cursor',)),obj({'query_id':ID,'owner_id':ID,'items':arr(ref('MemoryControl'),0,200),'next_cursor':text(),'exhausted':BOOL,'partial':BOOL,'gaps':arr(text())},('next_cursor',)),success='固定管理ID集合，逐页返回当前获准控制元数据；不要求旧正文可读。',extra=('cursor_expired','query_conflict'))
add('ExtractionCandidate',obj({'candidate_id':ID,'owner_id':ID,'revision':REV,'extraction_task_id':ID,'proposed_type':enum('fact','preference','inference','experience'),'content_ref':CR,'sources':arr(ref('SourceBinding'),1),'scope':ref('Scope'),'proposed_policy':ref('ContentPolicy'),'decision':enum('pending','saved','rejected'),'memory_ref':OR},('memory_ref',)))
add('ExtractionBundle',obj({'schema_version':const('extraction-candidates/1'),'extraction_id':ID,'extraction_task_id':ID,'candidates':arr(ref('ExtractionCandidate'))}))
add('CandidateRejectEvent',obj({'schema_version':const('candidate-reject/1'),'candidate_ref':OR,'reason':text()}))
method('memory.extract',obj({'extraction_id':ID,'home_id':ID,'input_refs':arr(CR,1),'checkpoint_ref':OR,'rule_ref':CP,'save_mode':enum('confirm','preauthorized'),'usage_authorization_refs':arr(AR,1),'limits':obj({'max_candidates':integer(1,100),'max_input_bytes':integer(1),'deadline':DT,'cost_reservation_ref':OR})},('checkpoint_ref',)),obj({'extraction_id':ID,'extraction_task_id':ID,'home_id':ID,'owner_id':ID,'input_digest':DIG,'state':const('queued')}),'command',success='有限输入、唯一Home任务映射和启动责任已保存；尚未生成或发布候选。',extra=('source_unavailable','source_closed','extraction_conflict','preauthorization_required'))
defs['MemoryWrite']=copy.deepcopy(base['MemoryWrite']);defs['MemoryWrite']['properties']['extraction_candidate_ref']=OR
add('MemoryViewFilter',obj({'types':arr(enum('fact','preference','inference','experience'),0,4),'scope':ref('Scope')}))
add('MemoryView',obj({'view_id':ID,'owner_id':ID,'recipient_id':ID,'filter':ref('MemoryViewFilter'),'projection':enum('metadata','content_refs'),'purpose':text(256),'retention_until':DT,'expires_at':DT,'lease_ref':OR,'revision':REV,'snapshot_cursor':text(),'change_cursor':text(),'state':enum('active','closed')},('lease_ref','change_cursor')))
add('MemoryViewChange',{'oneOf':[obj({'kind':const('upsert'),'sequence':integer(),'record':{'oneOf':[ref('MemoryRecord'),ref('MemoryControl')]}}),obj({'kind':const('tombstone'),'sequence':integer(),'memory_id':ID,'revision':REV})]})
method('memory.view.open',obj({'view_id':ID,'recipient_id':ID,'filter':ref('MemoryViewFilter'),'projection':enum('metadata','content_refs'),'purpose':text(256),'retention_until':DT,'expires_at':DT,'lease_ref':OR},('lease_ref',)),ref('MemoryView'),'command',success='保存获准视图、有限快照切点及发送责任；不授予永久离线使用。',extra=('view_conflict','source_unavailable'))
method('memory.view.pull',obj({'view_id':ID,'cursor':text(),'limit':integer(1,100)}),obj({'view_id':ID,'page_id':ID,'phase':enum('snapshot','changes'),'from_cursor':text(),'next_cursor':text(),'through_sequence':integer(),'items':arr(ref('MemoryViewChange')),'exhausted':BOOL}),target='payload.view_id',success='返回原视图连续快照或增量页；副本原子应用后才确认。',extra=('resnapshot_required','view_expired','source_unavailable'))
method('memory.view.ack',obj({'view_id':ID,'page_id':ID,'through_sequence':integer(),'applied_cursor':text()}),obj({'view_id':ID,'page_id':ID,'acked_sequence':integer(),'acked_cursor':text()}),'command','payload.view_id',success='持久保存已应用原页的连续ACK；不允许确认未交付页或跳过。',extra=('ack_gap','view_expired','resnapshot_required'))
method('memory.cleanup.get',obj({'object_ref':OR,'closure_revision':REV}),ref('CleanupReport'),target='payload.object_ref.owner_id',success='逐持有者报告停止、物理清理和残留；未确认不汇总完成。',extra=('source_unavailable',))
# Declarative Surface and fixed application events.
add('SurfaceField',obj({'name':text(64),'label':text(256),'type':enum('text','integer','boolean','choice','choices'),'required':BOOL,'max_length':integer(1,4096),'minimum':{'type':'integer'},'maximum':{'type':'integer'},'options':arr(obj({'id':text(64),'label':text(256)}),1),'max_choices':integer(1,100)},('max_length','minimum','maximum','options','max_choices')))
add('SurfaceInputSchema',obj({'fields':arr(ref('SurfaceField'),1,32)}))
add('SurfaceBlock',{'oneOf':[
obj({'kind':const('text'),'block_id':text(64),'content_ref':CR,'format':enum('plain','markdown')}),
obj({'kind':const('media'),'block_id':text(64),'content_ref':CR,'alt':text(512),'display':enum('image','audio','video','file')}),
obj({'kind':const('table'),'block_id':text(64),'columns':arr(text(128),1,20),'rows':arr(arr({'type':'string','maxLength':512},0,20),0,100)}),
obj({'kind':const('input'),'block_id':text(64),'request_ref':OR,'label':text(256),'input_schema':ref('SurfaceInputSchema')}),
obj({'kind':const('action'),'block_id':text(64),'request_ref':OR,'action_id':text(64),'label':text(256)}),
obj({'kind':const('status'),'block_id':text(64),'code':enum('queued','working','waiting','done','error','unavailable'),'label':text(256)})]})
add('SurfaceSnapshot',obj({'title':text(512),'blocks':arr(ref('SurfaceBlock')),'request_refs':arr(OR),'expires_at':DT,'source_revision':REV},('source_revision',)))
add('Surface',obj({'surface_id':ID,'surface_owner_id':ID,'app_binding':CP,'task_ref':ref('TaskRef'),'revision':REV,'snapshot':ref('SurfaceSnapshot')},('task_ref',)))
add('SurfaceSummary',obj({'surface_id':ID,'surface_owner_id':ID,'app_binding':CP,'task_ref':ref('TaskRef'),'revision':REV,'title':text(512),'expires_at':DT},('task_ref',)))
method('interaction.surface_create',obj({'surface_id':ID,'app_binding':CP,'task_ref':ref('TaskRef'),'snapshot':ref('SurfaceSnapshot')},('task_ref',)),ref('Surface'),'command',success='保存固定应用/任务绑定、完整快照与提示责任。',extra=('app_not_registered','surface_conflict','component_unsupported','request_binding'))
method('interaction.surface_read',obj({'known_revision':REV},('known_revision',)),{'oneOf':[obj({'status':const('snapshot'),'surface':ref('Surface'),'gaps':arr(text())}),obj({'status':const('not_modified'),'surface_id':ID,'revision':REV,'gaps':arr(text())})]},target='surface_id',success='按当前披露资格返回完整快照或未变化；缺材料单列。',extra=('source_unavailable','source_closed'))
method('interaction.surface_update',obj({'snapshot':ref('SurfaceSnapshot')}),ref('Surface'),'command','surface_id',True,'按原绑定处理器与源修订更新完整快照及提示责任。',('component_unsupported','request_binding','source_revision_conflict'))
method('interaction.surface_list',obj({'query_id':ID,'filters':obj({'app_ids':arr(ID,0,32),'task_refs':arr(ref('TaskRef'),0,32),'include_expired':BOOL}),'limit':integer(1,200),'cursor':text()},('cursor',)),obj({'query_id':ID,'owner_id':ID,'items':arr(ref('SurfaceSummary'),0,200),'next_cursor':text(),'exhausted':BOOL,'partial':BOOL,'gaps':arr(text()),'unreachable_endpoints':arr(ID)},('next_cursor',)),success='本owner有限目录逐页复核披露；跨端不可达项单列，不表示全局完整。',extra=('cursor_expired','query_conflict'))
method('interaction.present',obj({'endpoint_id':ID,'open':BOOL,'seen_revision':integer()}),obj({'surface_id':ID,'endpoint_id':ID,'intent_revision':REV,'open':BOOL,'seen_revision':integer()}),'command','surface_id',True,'保存本设备呈现意图；关闭不取消任务、不撤回已消费输入。',('presentation_conflict',))
add('ApplicationEventSubmission',obj({'event_id':ID,'surface_id':ID,'surface_revision':REV,'app_binding':CP,'event_type':text(128),'payload_ref':CR,'preview_refs':arr(CR),'target_service_id':ID,'target_command_id':ID,'state':enum('queued','sending','applied','rejected'),'receipt_ref':OR},('receipt_ref',)))
method('interaction.application_event',obj({'event_id':ID,'surface_id':ID,'surface_revision':REV,'app_binding':CP,'event_type':text(128),'payload_ref':CR,'preview_refs':arr(CR)}),ref('ApplicationEventSubmission'),'command','payload.surface_id',success='保存固定事件/处理器/原目标命令及转交责任；queued不证明领域消费。',extra=('app_not_registered','event_unsupported','request_binding','source_unavailable'))
add('InputRequestView',obj({'request_id':ID,'owner_id':ID,'revision':REV,'kind':enum('clarification','acceptance','application'),'task_ref':ref('TaskRef'),'schema':ref('SurfaceInputSchema'),'question_ref':CR,'deadline':DT,'required_content_refs':arr(CR),'allowed_actions':arr(text(64),1,32),'state':enum('open','consumed','expired','superseded'),'consumed_by':ID,'goal_revision':REV,'candidate_ref':CR,'candidate_hash':DIG},('task_ref','consumed_by','goal_revision','candidate_ref','candidate_hash')))
method('interaction.request_read',obj({'request_ref':OR}),obj({'request':ref('InputRequestView'),'gaps':arr(text())}),target='payload.request_ref.owner_id',success='实际请求负责端返回当前准确请求投影及预览依赖；旧修订拒绝，引用不授予披露资格。',extra=('source_unavailable','source_closed'))
# Context and plan documents use these schemas after content hash verification.
add('BrainArgumentBinding',obj({'target_pointer':text(512),'operation_id':ID,'source_pointer':text(512),'evidence_ref':CR}))
add('BrainPlanStep',obj({'step_id':text(64),'requirement_refs':arr(ID),'depends_on':arr(text(64),0,16),'instruction':text(),'action_template':{'oneOf':[ref('ActionInvoke'),ref('ActionDelegate')]},'argument_bindings':arr(ref('BrainArgumentBinding'),0,32)},('action_template','argument_bindings')))
add('BrainPlan',obj({'schema_version':const('brain-plan/1'),'plan_id':ID,'revision':REV,'task_ref':ref('TaskRef'),'goal_revision':REV,'steps':arr(ref('BrainPlanStep'),1,64),'source_refs':arr(CR)}))
add('BrainContext',obj({'schema_version':const('brain-context/1'),'task_ref':ref('TaskRef'),'snapshot_revision':REV,'goal_revision':REV,'control_revision':REV,'goal_ref':CR,'requirements':arr(ref('Requirement')),'control':enum('running','paused'),'plan_ref':nullable(CR),'facts':arr(obj({'kind':enum('operation','condition','input','resource'),'object_ref':OR,'content_ref':CR})),'assumptions':arr(text()),'unresolved_effects':arr(obj({'operation_id':ID,'effect':enum('unknown','not_started','not_applied','applied'),'owner_id':ID})),'materials':arr(obj({'content_ref':CR,'role':enum('evidence','memory','skill','history'),'source_refs':arr(CR),'byte_start':integer(),'byte_end':integer()},('byte_start','byte_end'))),'capabilities':arr(ref('CapabilityFixture')),'gaps':arr(obj({'required':BOOL,'reason':text(),'object_ref':OR},('object_ref',))),'input_manifest':arr(CR)}))
Path('.scratch/architecture-detail/content-protocol-patch.json').write_text(json.dumps({'defs':defs,'methods':methods},ensure_ascii=False,indent=2)+'\n')
print(len(defs),'definitions;',len(methods),'methods')
