# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'harness.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rharness.proto\x12\x0eharness.rpc.v1\"\x9a\x02\n\x0b\x43\x61llRequest\x12\x1a\n\x12logical_service_id\x18\x01 \x01(\t\x12\x16\n\x0c\x63ommand_json\x18\x02 \x01(\x0cH\x00\x12\x14\n\nquery_json\x18\x03 \x01(\x0cH\x00\x12\x1d\n\x13receipt_lookup_json\x18\x04 \x01(\x0cH\x00\x12\x1d\n\x13upload_reserve_json\x18\x05 \x01(\x0cH\x00\x12\x1c\n\x12upload_lookup_json\x18\x06 \x01(\x0cH\x00\x12\x1d\n\x13mirror_reserve_json\x18\x07 \x01(\x0cH\x00\x12\x1c\n\x12mirror_lookup_json\x18\x08 \x01(\x0cH\x00\x12\x1d\n\x13mirror_control_json\x18\t \x01(\x0cH\x00\x42\t\n\x07request\"\x91\x01\n\x0c\x43\x61llResponse\x12\x16\n\x0creceipt_json\x18\x01 \x01(\x0cH\x00\x12\x1b\n\x11query_result_json\x18\x02 \x01(\x0cH\x00\x12\x14\n\nerror_json\x18\x03 \x01(\x0cH\x00\x12\x15\n\x0bupload_json\x18\x04 \x01(\x0cH\x00\x12\x15\n\x0bmirror_json\x18\x05 \x01(\x0cH\x00\x42\x08\n\x06result\"6\n\x0c\x43hannelFrame\x12\x12\n\nframe_json\x18\x01 \x01(\x0c\x12\x12\n\nbinding_id\x18\x02 \x01(\t2\xa6\x01\n\x0eHarnessService\x12\x41\n\x04\x43\x61ll\x12\x1b.harness.rpc.v1.CallRequest\x1a\x1c.harness.rpc.v1.CallResponse\x12Q\n\x0f\x45ndpointChannel\x12\x1c.harness.rpc.v1.ChannelFrame\x1a\x1c.harness.rpc.v1.ChannelFrame(\x01\x30\x01\x42\x16Z\x14harness/rpc/v1;rpcv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'harness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024harness/rpc/v1;rpcv1'
  _globals['_CALLREQUEST']._serialized_start=34
  _globals['_CALLREQUEST']._serialized_end=316
  _globals['_CALLRESPONSE']._serialized_start=319
  _globals['_CALLRESPONSE']._serialized_end=464
  _globals['_CHANNELFRAME']._serialized_start=466
  _globals['_CHANNELFRAME']._serialized_end=520
  _globals['_HARNESSSERVICE']._serialized_start=523
  _globals['_HARNESSSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
