#!/usr/bin/env python3
"""从唯一 core Schema 生成 Go 记录和只读 Schema 快照。"""
import argparse
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/architecture/protocol/core.schema.json"
schema = json.loads(SOURCE.read_text())
defs = schema["$defs"]
primitive = {"Id": "string", "Digest": "string", "Time": "string", "Decimal": "string", "Revision": "uint64", "Count": "uint64"}

def field_name(name):
    special = {"id": "ID", "ids": "IDs", "url": "URL", "uri": "URI", "utc": "UTC", "ttl": "TTL", "gui": "GUI"}
    return "".join(special.get(p, p.capitalize()) for p in name.split("_"))

def go_type(s):
    if "$ref" in s:
        name = s["$ref"].split("/")[-1]
        return primitive.get(name, name)
    t = s.get("type")
    if t == "array": return "[]" + go_type(s["items"])
    if t == "object": return "json.RawMessage"
    if t == "boolean": return "bool"
    if t == "integer": return "uint64"
    if t == "number": return "float64"
    if t == "string" or "enum" in s: return "string"
    if "const" in s: return "uint64" if isinstance(s["const"], int) else "string"
    return "any"

lines = ["// Code generated by scripts/generate_core.py from docs/architecture/protocol/core.schema.json; DO NOT EDIT.", "package api", ""]
objects = [(n,s) for n,s in defs.items() if s.get("type") == "object" and n != "Command"]
if any(go_type(p) == "json.RawMessage" for _,s in objects for p in s.get("properties",{}).values()):
    lines += ['import "encoding/json"', ""]
for name, spec in objects:
    lines += [f"type {name} struct {{"]
    for field, fs in spec.get("properties", {}).items():
        typ = go_type(fs)
        optional = field not in spec.get("required", [])
        if optional and (typ in ("uint64", "bool", "float64") or typ in {n for n, _ in objects}):
            typ = "*" + typ
        lines += [f'\t{field_name(field)} {typ} `json:"{field}{",omitempty" if optional else ""}"`']
    lines += ["}", ""]
content = subprocess.run(["gofmt"], input="\n".join(lines), capture_output=True, text=True, check=True).stdout
outputs = {ROOT / "api/records.gen.go": content, ROOT / "api/schema/core.schema.json": SOURCE.read_text()}
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for path, data in outputs.items():
    if args.check:
        if not path.exists() or path.read_text() != data:
            raise SystemExit(f"generated asset drift: {path.relative_to(ROOT)}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(data)
print("core generated assets match" if args.check else "core assets generated")
