// Lerna schema generator v1.0.0. No unsupported schema keyword is ignored.
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { execFileSync } from 'node:child_process';
const source = 'contract/schema/1.0.0/values.json';
const schema = JSON.parse(readFileSync(source, 'utf8'));
const allowed = new Set([
  '$schema',
  '$id',
  '$defs',
  '$ref',
  'type',
  'properties',
  'required',
  'additionalProperties',
  'items',
  'maxItems',
  'minItems',
  'pattern',
  'format',
  'minLength',
  'maxLength',
  'enum',
  'description',
  'const',
  'allOf',
  'if',
  'then',
  'else',
]);
function audit(node) {
  for (const [key, value] of Object.entries(node)) {
    if (!allowed.has(key)) throw Error(`unsupported schema keyword: ${key}`);
    if (['properties', '$defs'].includes(key))
      Object.values(value).forEach(audit);
    if (['items', 'if', 'then', 'else'].includes(key)) audit(value);
    if (key === 'allOf') value.forEach(audit);
  }
  if (node.type === 'object' && node.additionalProperties !== false)
    throw Error('object must be closed');
}
audit(schema);
const title = (s) =>
  s
    .split('_')
    .map((s) => (s === 'id' ? 'ID' : s[0].toUpperCase() + s.slice(1)))
    .join('');
function type(s, lang) {
  if (s.$ref) {
    if (!s.$ref.startsWith('#/$defs/'))
      throw Error('external refs unsupported');
    return s.$ref.slice(8);
  }
  if (Array.isArray(s.type)) {
    if (JSON.stringify(s.type) !== '["string","null"]')
      throw Error('unsupported nullable type');
    return lang === 'go' ? '*string' : 'string | null';
  }
  if (s.enum) {
    if (lang === 'ts') return s.enum.map(JSON.stringify).join(' | ');
  }
  switch (s.type) {
    case 'string':
      return 'string';
    case 'boolean':
      return lang === 'go' ? 'bool' : 'boolean';
    case 'array':
      return lang === 'go'
        ? '[]' + type(s.items, lang)
        : `Array<${type(s.items, lang)}>`;
    case 'object':
      return lang === 'go'
        ? `struct {\n${Object.entries(s.properties)
            .map(
              ([k, v]) =>
                `${title(k)} ${s.required.includes(k) ? type(v, lang) : '*' + type(v, lang)} \x60json:"${k}${s.required.includes(k) ? '' : ',omitempty'}"\x60`,
            )
            .join('\n')}\n}`
        : `{\n${Object.entries(s.properties)
            .map(
              ([k, v]) =>
                `${k}${s.required.includes(k) ? '' : '?'}: ${type(v, lang)};`,
            )
            .join('\n')}\n}`;
    default:
      throw Error(`unsupported type ${s.type}`);
  }
}
let go = `// Code generated by scripts/generate.mjs v1.0.0 from ${source}; DO NOT EDIT.\npackage wire\n\n`;
let ts = `// Code generated by scripts/generate.mjs v1.0.0 from ${source}; DO NOT EDIT.\n`;
let aliases = `// Code generated by scripts/generate.mjs v1.0.0 from ${source}; DO NOT EDIT.\npackage contract\nimport wire "github.com/ruipengliu/lerna/contract/gen/go"\n`;
for (const [name, definition] of Object.entries(schema.$defs)) {
  go += `type ${name} ${type(definition, 'go')}\n`;
  ts += `export type ${name} = ${type(definition, 'ts')};\n`;
  aliases += `type ${name} = wire.${name}\n`;
}
aliases += `type Value interface { ${Object.keys(schema.$defs).join(' | ')} }\n`;
go += `const SchemaJSON = ${JSON.stringify(JSON.stringify(schema))}\n`;
ts += `export interface Values {\n${Object.keys(schema.$defs)
  .map((n) => `${n}: ${n};`)
  .join(
    '\n',
  )}\n}\nexport const schema = ${JSON.stringify(schema, null, 2)} as const;\n`;
for (const [path, content] of [
  ['contract/gen/go/values.go', go],
  ['contract/values.go', aliases],
  ['sdk/typescript/src/generated/values.ts', ts],
]) {
  const output = path.endsWith('.go')
    ? execFileSync('gofmt', { input: content, encoding: 'utf8' })
    : execFileSync('pnpm', ['exec', 'prettier', '--stdin-filepath', path], {
        input: content,
        encoding: 'utf8',
      });
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== output)
      throw Error(`stale generated file ${path}`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, output);
  }
}
