"""Generate the implemented component values from the sole JSON Schema source."""
import argparse
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = json.loads((ROOT / 'contracts/schemas/protocol.schema.json').read_text())['$defs']
METHODS = json.loads((ROOT / 'contracts/schemas/methods.json').read_text())['methods']

def name(value):
    words = re.split('_', value)
    return ''.join({'id':'ID', 'ids':'IDs', 'json':'JSON', 'uri':'URI', 'url':'URL',
                    'gui':'GUI'}.get(w, w[:1].upper() + w[1:]) for w in words)

selected = [m for m in METHODS if m.startswith(('task.', 'budget.'))]
selected += ['interaction.request_read']
roots = {METHODS[m][k] for m in selected for k in ('input', 'output')}
roots |= {'ContentRef', 'ComponentRef', 'Requirement', 'Task', 'Result', 'Invoke',
          'BrainContext', 'DecisionRequest', 'DecisionRecord', 'Proposal', 'Operation',
          'InputRequestView', 'ConditionResult', 'BrainPlan', 'ConfirmationRecord'}
needed = set()
def discover(value):
    if isinstance(value, list):
        for v in value: discover(v)
    elif isinstance(value, dict):
        ref = value.get('$ref')
        if ref:
            key = ref.split('/')[-1]
            if key not in needed:
                needed.add(key)
                discover(SCHEMA[key])
        for v in value.values(): discover(v)
for key in sorted(roots):
    needed.add(key)
    discover(SCHEMA[key])

definitions = {}
def typ(s, path):
    if '$ref' in s: return name(s['$ref'].split('/')[-1])
    union = s.get('oneOf', s.get('anyOf'))
    if union:
        other = [v for v in union if v.get('type') != 'null']
        if len(other) == 1 and len(other) != len(union): return '*' + typ(other[0], path)
        if all(v.get('type') == 'object' for v in union):
            props, required = {}, set(union[0].get('required', []))
            for v in union:
                required &= set(v.get('required', []))
                for k, p in v['properties'].items():
                    if k not in props:
                        props[k] = p
                    elif props[k] != p:
                        def primitive(x):
                            if '$ref' in x: return None
                            t = x.get('type')
                            if t in ('string', 'integer', 'number', 'boolean'): return t
                            c = x.get('const', x.get('enum', [None])[0])
                            return 'boolean' if isinstance(c, bool) else 'string' if isinstance(c, str) else None
                        a, b = primitive(props[k]), primitive(p)
                        if not a or a != b: props[k] = {}
            return typ({'type':'object', 'properties':props, 'required':sorted(required)}, path)
        return 'json.RawMessage'
    kind = s.get('type')
    if kind is None and ('enum' in s or 'const' in s):
        value = s.get('const', s.get('enum', [None])[0])
        kind = 'boolean' if isinstance(value, bool) else 'string' if isinstance(value, str) else None
    if kind == 'string': return 'string'
    if kind == 'integer': return 'int64'
    if kind == 'number': return 'json.Number'
    if kind == 'boolean': return 'bool'
    if kind == 'array': return '[]' + typ(s['items'], path + 'Item')
    if kind == 'object' and 'properties' in s:
        fields = []
        for k, v in s['properties'].items():
            field_type = typ(v, path + name(k))
            optional = k not in s.get('required', [])
            if optional and not field_type.startswith('*'): field_type = '*' + field_type
            fields.append('\t' + name(k) + ' ' + field_type + ' `json:"' + k + (',omitempty' if optional else '') + '"`')
        definitions[path] = 'struct {\n' + '\n'.join(fields) + '\n}'
        return path
    if kind == 'object': return 'map[string]json.RawMessage'
    return 'json.RawMessage'

for key in sorted(needed):
    n = name(key)
    t = typ(SCHEMA[key], n)
    if t != n: definitions[n] = '= ' + t

source = '// Code generated by tools/generate-domain.py from contracts/schemas/protocol.schema.json; DO NOT EDIT.\npackage api\n\nimport "encoding/json"\n\n'
source += '\n\n'.join('type ' + k + ' ' + v for k, v in sorted(definitions.items())) + '\n'
source = subprocess.run(['gofmt'], input=source, text=True, check=True, capture_output=True).stdout
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
destination = ROOT / 'api/values.gen.go'
if args.check:
    if not destination.exists() or destination.read_text() != source:
        raise SystemExit('api/values.gen.go differs; run make domain-generate')
else:
    destination.write_text(source)
print('domain contract values: ' + str(len(needed)) + ' source definitions')
