// Code generated by scripts/generate.mjs v1.0.0 from contract/schema/1.1.0/values.json; DO NOT EDIT.
package v1_1

import wire "github.com/ruipengliu/lerna/contract/gen/go/v1_1"

type ID = wire.ID
type Revision = wire.Revision
type Time = wire.Time
type Kind = wire.Kind
type OwnerRef = wire.OwnerRef
type ObjectRef = wire.ObjectRef
type ContentRef = wire.ContentRef
type Amount = wire.Amount
type Gap = wire.Gap
type ReadScope = wire.ReadScope
type CollectionView = wire.CollectionView
type ErrorCode = wire.ErrorCode
type PublicError = wire.PublicError
type MethodName = wire.MethodName
type ProfileName = wire.ProfileName
type ContractVersion = wire.ContractVersion
type TraceContext = wire.TraceContext
type CommandPayload = wire.CommandPayload
type CommandEnvelope = wire.CommandEnvelope
type CommandRef = wire.CommandRef
type CommandGetPayload = wire.CommandGetPayload
type CommandGetRequest = wire.CommandGetRequest
type CommandTarget = wire.CommandTarget
type NextAction = wire.NextAction
type CommandReceiptAccepted = wire.CommandReceiptAccepted
type CommandReceiptApplied = wire.CommandReceiptApplied
type CommandReceiptRejected = wire.CommandReceiptRejected

func NewCommandReceiptAccepted(value CommandReceiptAccepted) CommandReceipt {
	return wire.NewCommandReceiptAccepted(value)
}
func NewCommandReceiptApplied(value CommandReceiptApplied) CommandReceipt {
	return wire.NewCommandReceiptApplied(value)
}
func NewCommandReceiptRejected(value CommandReceiptRejected) CommandReceipt {
	return wire.NewCommandReceiptRejected(value)
}

type CommandReceipt = wire.CommandReceipt
type TaskObjectRef = wire.TaskObjectRef
type CommandProgressNone = wire.CommandProgressNone
type CommandProgressUnavailable = wire.CommandProgressUnavailable
type CommandProgressTask = wire.CommandProgressTask

func NewCommandProgressNone(value CommandProgressNone) CommandProgress {
	return wire.NewCommandProgressNone(value)
}
func NewCommandProgressUnavailable(value CommandProgressUnavailable) CommandProgress {
	return wire.NewCommandProgressUnavailable(value)
}
func NewCommandProgressTask(value CommandProgressTask) CommandProgress {
	return wire.NewCommandProgressTask(value)
}
func NewCommandProgressDecision(value CommandProgressDecision) CommandProgress {
	return wire.NewCommandProgressDecision(value)
}

type CommandProgress = wire.CommandProgress
type CommandGetResponseFound = wire.CommandGetResponseFound
type CommandGetResponseNotFound = wire.CommandGetResponseNotFound
type CommandGetResponseGone = wire.CommandGetResponseGone
type CommandGetResponseUnavailable = wire.CommandGetResponseUnavailable
type CommandGetResponseRejected = wire.CommandGetResponseRejected

func NewCommandGetResponseFound(value CommandGetResponseFound) CommandGetResponse {
	return wire.NewCommandGetResponseFound(value)
}
func NewCommandGetResponseNotFound(value CommandGetResponseNotFound) CommandGetResponse {
	return wire.NewCommandGetResponseNotFound(value)
}
func NewCommandGetResponseGone(value CommandGetResponseGone) CommandGetResponse {
	return wire.NewCommandGetResponseGone(value)
}
func NewCommandGetResponseUnavailable(value CommandGetResponseUnavailable) CommandGetResponse {
	return wire.NewCommandGetResponseUnavailable(value)
}
func NewCommandGetResponseRejected(value CommandGetResponseRejected) CommandGetResponse {
	return wire.NewCommandGetResponseRejected(value)
}

type CommandGetResponse = wire.CommandGetResponse
type TransportOutcomeReceived = wire.TransportOutcomeReceived
type TransportOutcomeCommitUnknown = wire.TransportOutcomeCommitUnknown

func NewTransportOutcomeReceived(value TransportOutcomeReceived) TransportOutcome {
	return wire.NewTransportOutcomeReceived(value)
}
func NewTransportOutcomeCommitUnknown(value TransportOutcomeCommitUnknown) TransportOutcome {
	return wire.NewTransportOutcomeCommitUnknown(value)
}

type TransportOutcome = wire.TransportOutcome
type DelegatedSubject = wire.DelegatedSubject
type SubjectBinding = wire.SubjectBinding
type SchemaDigest = wire.SchemaDigest
type MethodSupport = wire.MethodSupport
type NegotiationRequest = wire.NegotiationRequest
type DecisionRef = wire.DecisionRef
type SnapshotRef = wire.SnapshotRef
type RequirementRef = wire.RequirementRef
type CapabilityRef = wire.CapabilityRef
type BindingRef = wire.BindingRef
type UseRef = wire.UseRef
type InstallLockRef = wire.InstallLockRef
type ComponentRef = wire.ComponentRef
type DecisionLimits = wire.DecisionLimits
type DecisionUsage = wire.DecisionUsage
type DecisionDecidePayload = wire.DecisionDecidePayload
type DecisionGetPayload = wire.DecisionGetPayload
type ControlBasis = wire.ControlBasis
type DecisionCancelPayload = wire.DecisionCancelPayload
type DecisionDecideRequest = wire.DecisionDecideRequest
type DecisionGetRequest = wire.DecisionGetRequest
type DecisionCancelRequest = wire.DecisionCancelRequest
type RequirementDelta = wire.RequirementDelta
type ProposalAction = wire.ProposalAction
type ProposalEvidence = wire.ProposalEvidence
type ProposalAdvanceNone = wire.ProposalAdvanceNone
type ProposalAdvanceActions = wire.ProposalAdvanceActions
type ProposalAdvanceInputRequest = wire.ProposalAdvanceInputRequest
type ProposalAdvanceCandidateResult = wire.ProposalAdvanceCandidateResult
type ProposalAdvanceCannotContinue = wire.ProposalAdvanceCannotContinue

func NewProposalAdvanceNone(value ProposalAdvanceNone) ProposalAdvance {
	return wire.NewProposalAdvanceNone(value)
}
func NewProposalAdvanceActions(value ProposalAdvanceActions) ProposalAdvance {
	return wire.NewProposalAdvanceActions(value)
}
func NewProposalAdvanceInputRequest(value ProposalAdvanceInputRequest) ProposalAdvance {
	return wire.NewProposalAdvanceInputRequest(value)
}
func NewProposalAdvanceCandidateResult(value ProposalAdvanceCandidateResult) ProposalAdvance {
	return wire.NewProposalAdvanceCandidateResult(value)
}
func NewProposalAdvanceCannotContinue(value ProposalAdvanceCannotContinue) ProposalAdvance {
	return wire.NewProposalAdvanceCannotContinue(value)
}

type ProposalAdvance = wire.ProposalAdvance
type Proposal = wire.Proposal
type DecisionFailure = wire.DecisionFailure
type DecisionAccepted = wire.DecisionAccepted
type DecisionRunning = wire.DecisionRunning
type DecisionWaiting = wire.DecisionWaiting
type DecisionCompleted = wire.DecisionCompleted
type DecisionFailed = wire.DecisionFailed
type DecisionCancelled = wire.DecisionCancelled

func NewDecisionAccepted(value DecisionAccepted) Decision   { return wire.NewDecisionAccepted(value) }
func NewDecisionRunning(value DecisionRunning) Decision     { return wire.NewDecisionRunning(value) }
func NewDecisionWaiting(value DecisionWaiting) Decision     { return wire.NewDecisionWaiting(value) }
func NewDecisionCompleted(value DecisionCompleted) Decision { return wire.NewDecisionCompleted(value) }
func NewDecisionFailed(value DecisionFailed) Decision       { return wire.NewDecisionFailed(value) }
func NewDecisionCancelled(value DecisionCancelled) Decision { return wire.NewDecisionCancelled(value) }

type Decision = wire.Decision
type DecisionGetResponseFound = wire.DecisionGetResponseFound
type DecisionGetResponseResultUnavailable = wire.DecisionGetResponseResultUnavailable
type DecisionGetResponseUnavailable = wire.DecisionGetResponseUnavailable
type DecisionGetResponseRejected = wire.DecisionGetResponseRejected

func NewDecisionGetResponseFound(value DecisionGetResponseFound) DecisionGetResponse {
	return wire.NewDecisionGetResponseFound(value)
}
func NewDecisionGetResponseResultUnavailable(value DecisionGetResponseResultUnavailable) DecisionGetResponse {
	return wire.NewDecisionGetResponseResultUnavailable(value)
}
func NewDecisionGetResponseUnavailable(value DecisionGetResponseUnavailable) DecisionGetResponse {
	return wire.NewDecisionGetResponseUnavailable(value)
}
func NewDecisionGetResponseRejected(value DecisionGetResponseRejected) DecisionGetResponse {
	return wire.NewDecisionGetResponseRejected(value)
}

type DecisionGetResponse = wire.DecisionGetResponse
type CommandProgressDecision = wire.CommandProgressDecision
type Value interface {
	ID | Revision | Time | Kind | OwnerRef | ObjectRef | ContentRef | Amount | Gap | ReadScope | CollectionView | ErrorCode | PublicError | MethodName | ProfileName | ContractVersion | TraceContext | CommandPayload | CommandEnvelope | CommandRef | CommandGetPayload | CommandGetRequest | CommandTarget | NextAction | CommandReceiptAccepted | CommandReceiptApplied | CommandReceiptRejected | CommandReceipt | TaskObjectRef | CommandProgressNone | CommandProgressUnavailable | CommandProgressTask | CommandProgress | CommandGetResponseFound | CommandGetResponseNotFound | CommandGetResponseGone | CommandGetResponseUnavailable | CommandGetResponseRejected | CommandGetResponse | TransportOutcomeReceived | TransportOutcomeCommitUnknown | TransportOutcome | DelegatedSubject | SubjectBinding | SchemaDigest | MethodSupport | NegotiationRequest | DecisionRef | SnapshotRef | RequirementRef | CapabilityRef | BindingRef | UseRef | InstallLockRef | ComponentRef | DecisionLimits | DecisionUsage | DecisionDecidePayload | DecisionGetPayload | ControlBasis | DecisionCancelPayload | DecisionDecideRequest | DecisionGetRequest | DecisionCancelRequest | RequirementDelta | ProposalAction | ProposalEvidence | ProposalAdvanceNone | ProposalAdvanceActions | ProposalAdvanceInputRequest | ProposalAdvanceCandidateResult | ProposalAdvanceCannotContinue | ProposalAdvance | Proposal | DecisionFailure | DecisionAccepted | DecisionRunning | DecisionWaiting | DecisionCompleted | DecisionFailed | DecisionCancelled | Decision | DecisionGetResponseFound | DecisionGetResponseResultUnavailable | DecisionGetResponseUnavailable | DecisionGetResponseRejected | DecisionGetResponse | CommandProgressDecision
}
