// Code generated by scripts/generate_core.py from docs/architecture/protocol/core.schema.json; DO NOT EDIT.
package api

type Amount struct {
	Unit  string `json:"unit"`
	Value string `json:"value"`
}

type ObjectRef struct {
	OwnerID  string `json:"owner_id"`
	ObjectID string `json:"object_id"`
	Revision uint64 `json:"revision"`
	TenantID string `json:"tenant_id"`
}

type ComponentRef struct {
	ComponentID string `json:"component_id"`
	Version     string `json:"version"`
	Digest      string `json:"digest"`
}

type ContentRef struct {
	TenantID   string `json:"tenant_id"`
	OwnerID    string `json:"owner_id"`
	ContentID  string `json:"content_id"`
	Version    uint64 `json:"version"`
	Hash       string `json:"hash"`
	MediaType  string `json:"media_type"`
	ByteLength uint64 `json:"byte_length"`
}

type CollectionSummary struct {
	CollectionRevision uint64 `json:"collection_revision"`
	TotalCount         uint64 `json:"total_count"`
	UnresolvedCount    uint64 `json:"unresolved_count"`
	ItemsCursor        string `json:"items_cursor,omitempty"`
	Complete           bool   `json:"complete"`
}

type BudgetBalance struct {
	Unit     string `json:"unit"`
	Limit    string `json:"limit"`
	Reserved string `json:"reserved"`
	Spent    string `json:"spent"`
}

type Requirement struct {
	RequirementID     string           `json:"requirement_id"`
	Revision          uint64           `json:"revision"`
	Kind              string           `json:"kind"`
	StatementRef      ContentRef       `json:"statement_ref"`
	SourceRefs        []SourceEvidence `json:"source_refs"`
	Origin            string           `json:"origin"`
	RuleRef           ComponentRef     `json:"rule_ref"`
	RuleParametersRef *ContentRef      `json:"rule_parameters_ref,omitempty"`
	Required          bool             `json:"required"`
	AdoptionID        string           `json:"adoption_id"`
}

type WaitReason struct {
	Kind            string     `json:"kind"`
	ObjectRef       *ObjectRef `json:"object_ref,omitempty"`
	ResumeCondition string     `json:"resume_condition"`
	NextCheckAt     string     `json:"next_check_at,omitempty"`
}

type Task struct {
	TenantID           string            `json:"tenant_id"`
	TaskID             string            `json:"task_id"`
	OrchestratorID     string            `json:"orchestrator_id"`
	SubmitCommandID    string            `json:"submit_command_id"`
	GoalRef            ContentRef        `json:"goal_ref"`
	GoalRevision       uint64            `json:"goal_revision"`
	ControlRevision    uint64            `json:"control_revision"`
	Revision           uint64            `json:"revision"`
	PolicyRef          ComponentRef      `json:"policy_ref"`
	Requirements       []Requirement     `json:"requirements"`
	Deadline           string            `json:"deadline"`
	Status             string            `json:"status"`
	Control            string            `json:"control"`
	WaitReasons        []WaitReason      `json:"wait_reasons"`
	Budget             []BudgetBalance   `json:"budget"`
	OpenEffects        CollectionSummary `json:"open_effects"`
	AccountingOpen     bool              `json:"accounting_open"`
	ResultRef          *ObjectRef        `json:"result_ref,omitempty"`
	AcceptanceRef      *ObjectRef        `json:"acceptance_ref,omitempty"`
	RequirementsState  string            `json:"requirements_state"`
	RequirementsDigest string            `json:"requirements_digest"`
	CurrentCoverageRef *ObjectRef        `json:"current_coverage_ref,omitempty"`
}

type Operation struct {
	OperationID    string            `json:"operation_id"`
	OwnerID        string            `json:"owner_id"`
	TaskRef        ObjectRef         `json:"task_ref"`
	Revision       uint64            `json:"revision"`
	ExecutionState string            `json:"execution_state"`
	Effect         string            `json:"effect"`
	MayApplyLater  any               `json:"may_apply_later"`
	Attempts       CollectionSummary `json:"attempts"`
	EvidenceRefs   []ContentRef      `json:"evidence_refs"`
	ResultRef      *ContentRef       `json:"result_ref,omitempty"`
	Usage          []Amount          `json:"usage"`
	UsageFinal     bool              `json:"usage_final"`
	NextAction     string            `json:"next_action"`
}

type ConditionResult struct {
	CheckID             string       `json:"check_id"`
	TaskID              string       `json:"task_id"`
	GoalRevision        uint64       `json:"goal_revision"`
	RequirementID       string       `json:"requirement_id"`
	ArtifactRef         ContentRef   `json:"artifact_ref"`
	RuleRef             ComponentRef `json:"rule_ref"`
	EvaluatorRef        ComponentRef `json:"evaluator_ref"`
	Verdict             string       `json:"verdict"`
	Applicability       string       `json:"applicability"`
	Basis               string       `json:"basis"`
	EvidenceRefs        []ContentRef `json:"evidence_refs"`
	RequirementRevision uint64       `json:"requirement_revision"`
	ObservedAt          string       `json:"observed_at,omitempty"`
	ScopeRef            ContentRef   `json:"scope_ref"`
	CheckedAt           string       `json:"checked_at"`
}

type Result struct {
	TaskID           string            `json:"task_id"`
	GoalRevision     uint64            `json:"goal_revision"`
	ArtifactRefs     []ContentRef      `json:"artifact_refs"`
	CompletionBasis  string            `json:"completion_basis"`
	ConditionResults []ConditionResult `json:"condition_results"`
	CoverageRef      ObjectRef         `json:"coverage_ref"`
	Limitations      []string          `json:"limitations"`
	CompletedAt      string            `json:"completed_at"`
	ResultID         string            `json:"result_id"`
	Revision         uint64            `json:"revision"`
}

type DecisionDispatchIntent struct {
	DecisionID       string       `json:"decision_id"`
	TaskRef          ObjectRef    `json:"task_ref"`
	SnapshotRef      ContentRef   `json:"snapshot_ref"`
	SnapshotRevision uint64       `json:"snapshot_revision"`
	ModelProfileRef  ComponentRef `json:"model_profile_ref"`
	BrainOwnerID     string       `json:"brain_owner_id"`
	CommandID        string       `json:"command_id"`
	IntentHash       string       `json:"intent_hash"`
}

type DecisionRecord struct {
	DecisionID           string      `json:"decision_id"`
	OwnerID              string      `json:"owner_id"`
	Revision             uint64      `json:"revision"`
	SnapshotRevision     uint64      `json:"snapshot_revision"`
	Status               string      `json:"status"`
	SendStarted          bool        `json:"send_started"`
	PhysicalRequestCount uint64      `json:"physical_request_count"`
	ProposalRef          *ContentRef `json:"proposal_ref,omitempty"`
	Usage                []Amount    `json:"usage"`
	UsageFinal           bool        `json:"usage_final"`
}

type Grant struct {
	GrantID    string    `json:"grant_id"`
	OwnerID    string    `json:"owner_id"`
	Revision   uint64    `json:"revision"`
	SubjectRef ObjectRef `json:"subject_ref"`
	Resources  []string  `json:"resources"`
	Actions    []string  `json:"actions"`
	Purposes   []string  `json:"purposes"`
	Recipients []string  `json:"recipients"`
	Locations  []string  `json:"locations"`
	Mode       string    `json:"mode"`
	State      string    `json:"state"`
	NotBefore  string    `json:"not_before"`
	ExpiresAt  string    `json:"expires_at"`
	Limits     []Amount  `json:"limits"`
}

type Confirmation struct {
	RequestID             string       `json:"request_id"`
	OwnerID               string       `json:"owner_id"`
	Revision              uint64       `json:"revision"`
	OriginalCommandID     string       `json:"original_command_id"`
	IntentHash            string       `json:"intent_hash"`
	PreviewRefs           []ContentRef `json:"preview_refs"`
	ExpiresAt             string       `json:"expires_at"`
	State                 string       `json:"state"`
	ConsumedBy            string       `json:"consumed_by,omitempty"`
	ConsumedAt            string       `json:"consumed_at,omitempty"`
	Challenge             string       `json:"challenge"`
	TrustedUserSessionRef ObjectRef    `json:"trusted_user_session_ref"`
	DecidedBy             string       `json:"decided_by,omitempty"`
	DecidedAt             string       `json:"decided_at,omitempty"`
	OriginalCommandRef    ContentRef   `json:"original_command_ref"`
}

type UsageSnapshot struct {
	SourceRef      ObjectRef    `json:"source_ref"`
	UsageRevision  uint64       `json:"usage_revision"`
	UsageDigest    string       `json:"usage_digest"`
	Cumulative     []Amount     `json:"cumulative"`
	SpendingClosed bool         `json:"spending_closed"`
	UsageFinal     bool         `json:"usage_final"`
	ProofRefs      []ContentRef `json:"proof_refs"`
}

type AllocationClosure struct {
	AllocationID   string     `json:"allocation_id"`
	ParentOwnerID  string     `json:"parent_owner_id"`
	ReceiverID     string     `json:"receiver_id"`
	SpendingClosed uint64     `json:"spending_closed"`
	ClosedAt       string     `json:"closed_at"`
	UsageRevision  uint64     `json:"usage_revision"`
	FinalUsage     []Amount   `json:"final_usage"`
	ProofRef       ContentRef `json:"proof_ref"`
}

type Job struct {
	JobID             string    `json:"job_id"`
	OwnerID           string    `json:"owner_id"`
	TenantID          string    `json:"tenant_id"`
	ResponsibilityKey string    `json:"responsibility_key"`
	Kind              string    `json:"kind"`
	SourceRef         ObjectRef `json:"source_ref"`
	State             string    `json:"state"`
	DueAt             string    `json:"due_at"`
	WorkRevision      uint64    `json:"work_revision"`
	LeaseEpoch        uint64    `json:"lease_epoch"`
	HolderID          string    `json:"holder_id,omitempty"`
	LeaseUntil        string    `json:"lease_until,omitempty"`
}

type ControlSnapshot struct {
	OrchestratorID  string     `json:"orchestrator_id"`
	TaskID          string     `json:"task_id"`
	GoalRevision    uint64     `json:"goal_revision"`
	ControlRevision uint64     `json:"control_revision"`
	Status          string     `json:"status"`
	Control         string     `json:"control"`
	IssuedAt        string     `json:"issued_at"`
	StartBefore     string     `json:"start_before"`
	ProofRef        ContentRef `json:"proof_ref"`
	WindowID        string     `json:"window_id"`
}

type DelegationContext struct {
	DelegationID          string          `json:"delegation_id"`
	ParentTaskRef         ObjectRef       `json:"parent_task_ref"`
	ParentGoalRevision    uint64          `json:"parent_goal_revision"`
	AncestorTaskRefs      []ObjectRef     `json:"ancestor_task_refs"`
	AgentBindingRef       ObjectRef       `json:"agent_binding_ref"`
	AllocationRef         ObjectRef       `json:"allocation_ref"`
	PermissionRefs        []ObjectRef     `json:"permission_refs"`
	ParentControlSnapshot ControlSnapshot `json:"parent_control_snapshot"`
	ContextDigest         string          `json:"context_digest"`
	ParentProofRef        ContentRef      `json:"parent_proof_ref"`
}

type SourceEvidence struct {
	ContentRef    ContentRef `json:"content_ref"`
	SourceKind    string     `json:"source_kind"`
	SubmissionRef *ObjectRef `json:"submission_ref,omitempty"`
	Locator       string     `json:"locator,omitempty"`
}

type RequirementRef struct {
	RequirementID string `json:"requirement_id"`
	Revision      uint64 `json:"revision"`
}

type RequirementCandidate struct {
	CandidateKey          string           `json:"candidate_key"`
	ReplacesRequirementID string           `json:"replaces_requirement_id,omitempty"`
	Kind                  string           `json:"kind"`
	StatementRef          ContentRef       `json:"statement_ref"`
	SourceRefs            []SourceEvidence `json:"source_refs"`
	Origin                string           `json:"origin"`
	RuleRef               ComponentRef     `json:"rule_ref"`
	RuleParametersRef     *ContentRef      `json:"rule_parameters_ref,omitempty"`
	Required              bool             `json:"required"`
	OpenQuestions         []string         `json:"open_questions"`
	ReplacesRevision      *uint64          `json:"replaces_revision,omitempty"`
}

type RequirementDelta struct {
	BaseGoalRevision uint64                 `json:"base_goal_revision"`
	Candidates       []RequirementCandidate `json:"candidates"`
	ReasonRef        ContentRef             `json:"reason_ref"`
}

type GoalRevision struct {
	TaskRef            ObjectRef        `json:"task_ref"`
	GoalRevision       uint64           `json:"goal_revision"`
	GoalRef            ContentRef       `json:"goal_ref"`
	SourceRefs         []SourceEvidence `json:"source_refs"`
	Requirements       []RequirementRef `json:"requirements"`
	RequirementsDigest string           `json:"requirements_digest"`
	ChangeKind         string           `json:"change_kind"`
	CauseRef           ObjectRef        `json:"cause_ref"`
	CreatedAt          string           `json:"created_at"`
}

type RequirementMapping struct {
	CandidateKey  string `json:"candidate_key"`
	RequirementID string `json:"requirement_id"`
	Revision      uint64 `json:"revision"`
}

type RequirementAdoption struct {
	AdoptionID          string               `json:"adoption_id"`
	TaskRef             ObjectRef            `json:"task_ref"`
	SourceKind          string               `json:"source_kind"`
	SourceRef           ObjectRef            `json:"source_ref"`
	BaseGoalRevision    uint64               `json:"base_goal_revision"`
	ResultGoalRevision  uint64               `json:"result_goal_revision"`
	Outcome             string               `json:"outcome"`
	Mappings            []RequirementMapping `json:"mappings"`
	ValidationReportRef ContentRef           `json:"validation_report_ref"`
	ReasonCodes         []string             `json:"reason_codes"`
	DecidedAt           string               `json:"decided_at"`
}

type GoalCoverage struct {
	CoverageID         string       `json:"coverage_id"`
	TaskRef            ObjectRef    `json:"task_ref"`
	GoalRevision       uint64       `json:"goal_revision"`
	GoalRef            ContentRef   `json:"goal_ref"`
	RequirementsDigest string       `json:"requirements_digest"`
	MappingReportRef   ContentRef   `json:"mapping_report_ref"`
	RuleRef            ComponentRef `json:"rule_ref"`
	EvaluatorRef       ComponentRef `json:"evaluator_ref"`
	OperationRef       *ObjectRef   `json:"operation_ref,omitempty"`
	Verdict            string       `json:"verdict"`
	Applicability      string       `json:"applicability"`
	CheckedAt          string       `json:"checked_at"`
	Revision           uint64       `json:"revision"`
}

type Claim struct {
	JobID                string `json:"job_id"`
	OwnerID              string `json:"owner_id"`
	TenantID             string `json:"tenant_id"`
	HolderID             string `json:"holder_id"`
	LeaseEpoch           uint64 `json:"lease_epoch"`
	LeaseUntil           string `json:"lease_until"`
	ObservedWorkRevision uint64 `json:"observed_work_revision"`
}

type Session struct {
	SessionID       string `json:"session_id"`
	TenantID        string `json:"tenant_id"`
	OwnerID         string `json:"owner_id"`
	Revision        uint64 `json:"revision"`
	State           string `json:"state"`
	DefaultBranchID string `json:"default_branch_id"`
	CreatedAt       string `json:"created_at"`
}

type Branch struct {
	BranchID        string       `json:"branch_id"`
	SessionRef      ObjectRef    `json:"session_ref"`
	Revision        uint64       `json:"revision"`
	HeadMessageID   string       `json:"head_message_id,omitempty"`
	SourceBranchRef *ObjectRef   `json:"source_branch_ref,omitempty"`
	HistoryCutoff   uint64       `json:"history_cutoff"`
	ConfigRef       ComponentRef `json:"config_ref"`
}

type Message struct {
	MessageID       string     `json:"message_id"`
	SessionRef      ObjectRef  `json:"session_ref"`
	BranchID        string     `json:"branch_id"`
	Seq             uint64     `json:"seq"`
	ParentMessageID string     `json:"parent_message_id,omitempty"`
	Role            string     `json:"role"`
	ContentRef      ContentRef `json:"content_ref"`
	SubmissionRef   *ObjectRef `json:"submission_ref,omitempty"`
	CreatedAt       string     `json:"created_at"`
}

type Submission struct {
	SubmissionID         string     `json:"submission_id"`
	TenantID             string     `json:"tenant_id"`
	OwnerID              string     `json:"owner_id"`
	Revision             uint64     `json:"revision"`
	SessionRef           ObjectRef  `json:"session_ref"`
	BranchID             string     `json:"branch_id"`
	MessageID            string     `json:"message_id"`
	Seq                  uint64     `json:"seq"`
	Kind                 string     `json:"kind"`
	ContentRef           ContentRef `json:"content_ref"`
	HistoryCutoff        uint64     `json:"history_cutoff"`
	TargetTaskRef        *ObjectRef `json:"target_task_ref,omitempty"`
	PredecessorTaskRef   *ObjectRef `json:"predecessor_task_ref,omitempty"`
	ExpectedGoalRevision *uint64    `json:"expected_goal_revision,omitempty"`
	RequestRef           *ObjectRef `json:"request_ref,omitempty"`
	DispatchCommandRef   *ObjectRef `json:"dispatch_command_ref,omitempty"`
	State                string     `json:"state"`
	WithdrawalRequested  bool       `json:"withdrawal_requested"`
	TaskRef              *ObjectRef `json:"task_ref,omitempty"`
	CreatedAt            string     `json:"created_at"`
}

type InputRequest struct {
	RequestID       string       `json:"request_id"`
	TenantID        string       `json:"tenant_id"`
	OwnerID         string       `json:"owner_id"`
	Revision        uint64       `json:"revision"`
	TargetRef       ObjectRef    `json:"target_ref"`
	GoalRevision    *uint64      `json:"goal_revision,omitempty"`
	Purpose         string       `json:"purpose"`
	QuestionRef     ContentRef   `json:"question_ref"`
	AnswerSchemaRef ComponentRef `json:"answer_schema_ref"`
	PreviewRefs     []ContentRef `json:"preview_refs"`
	ExpiresAt       string       `json:"expires_at"`
	State           string       `json:"state"`
	AnswerRef       *ContentRef  `json:"answer_ref,omitempty"`
	ConsumedBy      string       `json:"consumed_by,omitempty"`
	AnsweredAt      string       `json:"answered_at,omitempty"`
	CandidateRef    *ContentRef  `json:"candidate_ref,omitempty"`
	LimitationsRef  *ContentRef  `json:"limitations_ref,omitempty"`
}

type RuleDefinition struct {
	RuleRef                   ComponentRef `json:"rule_ref"`
	Kind                      string       `json:"kind"`
	ParametersSchemaRef       ComponentRef `json:"parameters_schema_ref"`
	Predicate                 string       `json:"predicate"`
	AllowedBasis              []string     `json:"allowed_basis"`
	AllowUserAcceptance       bool         `json:"allow_user_acceptance"`
	RequiredEvidenceSchemaRef ComponentRef `json:"required_evidence_schema_ref"`
	ScopeSchemaRef            ComponentRef `json:"scope_schema_ref"`
	MaxObservationAgeSeconds  *uint64      `json:"max_observation_age_seconds,omitempty"`
	RiskClass                 string       `json:"risk_class"`
	ApplicabilityPolicyRef    ComponentRef `json:"applicability_policy_ref"`
}

type GoalDocument struct {
	FormatVersion  uint64       `json:"format_version"`
	InitialGoalRef ContentRef   `json:"initial_goal_ref"`
	AmendmentRefs  []ContentRef `json:"amendment_refs"`
}
