// Code generated by tools/generate-domain.py from contracts/schemas/protocol.schema.json; DO NOT EDIT.
package api

import "encoding/json"

type ActionDelegate struct {
	ActionKey       string            `json:"action_key"`
	Type            string            `json:"type"`
	Purpose         string            `json:"purpose"`
	RequirementRefs []string          `json:"requirement_refs"`
	EvidenceRefs    []ContentRef      `json:"evidence_refs"`
	Delegation      DelegationRequest `json:"delegation"`
}

type ActionInvoke struct {
	ActionKey       string                     `json:"action_key"`
	Type            string                     `json:"type"`
	Purpose         string                     `json:"purpose"`
	RequirementRefs []string                   `json:"requirement_refs"`
	EvidenceRefs    []ContentRef               `json:"evidence_refs"`
	CapabilityRef   ComponentRef               `json:"capability_ref"`
	BindingRef      BindingRef                 `json:"binding_ref"`
	Arguments       map[string]json.RawMessage `json:"arguments"`
}

type AgentBinding struct {
	AgentRef   ComponentRef `json:"agent_ref"`
	AdapterRef ComponentRef `json:"adapter_ref"`
	EndpointID string       `json:"endpoint_id"`
}

type Amount struct {
	Unit   string `json:"unit"`
	Amount string `json:"amount"`
}

type ApprovalBatch struct {
	BatchID             Id                 `json:"batch_id"`
	Targets             []Id               `json:"targets"`
	ObservationWindowMs int64              `json:"observation_window_ms"`
	MinimumSamples      int64              `json:"minimum_samples"`
	StopRules           []EvaluationMetric `json:"stop_rules"`
}

type Attempt struct {
	AttemptID  string  `json:"attempt_id"`
	PreparedAt string  `json:"prepared_at"`
	SentAt     *string `json:"sent_at,omitempty"`
	TargetKey  *string `json:"target_key,omitempty"`
	Error      *Error  `json:"error,omitempty"`
}

type AuthorizationRef struct {
	Kind     string `json:"kind"`
	OwnerID  string `json:"owner_id"`
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
}

type BindingRef struct {
	BindingID string `json:"binding_id"`
	Revision  int64  `json:"revision"`
}

type BrainArgumentBinding struct {
	TargetPointer string            `json:"target_pointer"`
	Source        BrainOutputSource `json:"source"`
}

type BrainContext struct {
	SchemaVersion     string                              `json:"schema_version"`
	TaskRef           TaskRef                             `json:"task_ref"`
	SnapshotRevision  Revision                            `json:"snapshot_revision"`
	GoalRevision      Revision                            `json:"goal_revision"`
	ControlRevision   Revision                            `json:"control_revision"`
	GoalRef           ContentRef                          `json:"goal_ref"`
	Requirements      []Requirement                       `json:"requirements"`
	Control           string                              `json:"control"`
	PlanRef           *ContentRef                         `json:"plan_ref"`
	Facts             []BrainContextFactsItem             `json:"facts"`
	Assumptions       []string                            `json:"assumptions"`
	UnresolvedEffects []BrainContextUnresolvedEffectsItem `json:"unresolved_effects"`
	Materials         []BrainContextMaterialsItem         `json:"materials"`
	Capabilities      []CapabilityFixture                 `json:"capabilities"`
	Gaps              []BrainContextGapsItem              `json:"gaps"`
	InputManifest     []ContentRef                        `json:"input_manifest"`
}

type BrainContextFactsItem struct {
	Kind       string     `json:"kind"`
	ObjectRef  ObjectRef  `json:"object_ref"`
	ContentRef ContentRef `json:"content_ref"`
}

type BrainContextGapsItem struct {
	Required  bool       `json:"required"`
	Reason    string     `json:"reason"`
	ObjectRef *ObjectRef `json:"object_ref,omitempty"`
}

type BrainContextMaterialsItem struct {
	ContentRef ContentRef   `json:"content_ref"`
	Role       string       `json:"role"`
	SourceRefs []ContentRef `json:"source_refs"`
	ByteStart  *int64       `json:"byte_start,omitempty"`
	ByteEnd    *int64       `json:"byte_end,omitempty"`
}

type BrainContextUnresolvedEffectsItem struct {
	OperationID Id     `json:"operation_id"`
	Effect      string `json:"effect"`
	OwnerID     Id     `json:"owner_id"`
}

type BrainOutputSource struct {
	Kind          string      `json:"kind"`
	OperationID   *Id         `json:"operation_id,omitempty"`
	EvidenceRef   *ContentRef `json:"evidence_ref,omitempty"`
	SourcePointer string      `json:"source_pointer"`
	StepID        *string     `json:"step_id,omitempty"`
}

type BrainPassCondition struct {
	RequirementID Id           `json:"requirement_id"`
	RuleRef       ComponentRef `json:"rule_ref"`
	ArtifactRef   ContentRef   `json:"artifact_ref"`
}

type BrainPlan struct {
	SchemaVersion string          `json:"schema_version"`
	PlanID        Id              `json:"plan_id"`
	Revision      Revision        `json:"revision"`
	TaskRef       TaskRef         `json:"task_ref"`
	GoalRevision  Revision        `json:"goal_revision"`
	Steps         []BrainPlanStep `json:"steps"`
	SourceRefs    []ContentRef    `json:"source_refs"`
}

type BrainPlanStep struct {
	StepID           string                  `json:"step_id"`
	RequirementRefs  []Id                    `json:"requirement_refs"`
	DependsOn        []string                `json:"depends_on"`
	PassConditions   *[]BrainPassCondition   `json:"pass_conditions,omitempty"`
	Instruction      string                  `json:"instruction"`
	ActionTemplate   *json.RawMessage        `json:"action_template,omitempty"`
	ArgumentBindings *[]BrainArgumentBinding `json:"argument_bindings,omitempty"`
}

type BudgetAllocateInput struct {
	AllocationID Id            `json:"allocation_id"`
	ParentTaskID Id            `json:"parent_task_id"`
	ReceiverID   Id            `json:"receiver_id"`
	Limits       []BudgetLimit `json:"limits"`
	ExpiresAt    string        `json:"expires_at"`
}

type BudgetAllocateOutput = RuntimeBudgetAllocation

type BudgetBalance struct {
	Unit     string `json:"unit"`
	Limit    Amount `json:"limit"`
	Spent    Amount `json:"spent"`
	Reserved Amount `json:"reserved"`
}

type BudgetCloseInput struct {
	SenderOrchestratorID Id        `json:"sender_orchestrator_id"`
	ParentDelegationID   Id        `json:"parent_delegation_id"`
	AllocationRef        ObjectRef `json:"allocation_ref"`
	AllocationCommandID  Id        `json:"allocation_command_id"`
	Reason               string    `json:"reason"`
}

type BudgetCloseOutput = RuntimeBudgetReceiver

type BudgetLimit struct {
	Unit  string `json:"unit"`
	Limit string `json:"limit"`
}

type BudgetReadInput struct {
	Role string `json:"role"`
}

type BudgetReadOutput struct {
	Role       string                   `json:"role"`
	Allocation *RuntimeBudgetAllocation `json:"allocation,omitempty"`
	Receiver   *RuntimeBudgetReceiver   `json:"receiver,omitempty"`
}

type BudgetSettleInput struct {
	AllocationID Id                   `json:"allocation_id"`
	Closure      RuntimeBudgetClosure `json:"closure"`
}

type BudgetSettleOutput = RuntimeBudgetAllocation

type CapabilityFixture struct {
	CapabilityRef       ComponentRef               `json:"capability_ref"`
	BindingRef          BindingRef                 `json:"binding_ref"`
	InputSchema         map[string]json.RawMessage `json:"input_schema"`
	SemanticOperationID *string                    `json:"semantic_operation_id,omitempty"`
	EffectClass         *string                    `json:"effect_class,omitempty"`
}

type ComponentRef struct {
	ID      string `json:"id"`
	Version string `json:"version"`
	Digest  string `json:"digest"`
}

type ConditionResult struct {
	RequirementID string       `json:"requirement_id"`
	GoalRevision  int64        `json:"goal_revision"`
	ArtifactRef   ContentRef   `json:"artifact_ref"`
	Verdict       string       `json:"verdict"`
	Basis         string       `json:"basis"`
	EvidenceRefs  []ContentRef `json:"evidence_refs"`
	EvaluatorRef  ComponentRef `json:"evaluator_ref"`
}

type ConfirmationConsumerCommand struct {
	CommandID        Id              `json:"command_id"`
	Method           string          `json:"method"`
	TargetID         Id              `json:"target_id"`
	ExpiresAt        string          `json:"expires_at"`
	Payload          json.RawMessage `json:"payload"`
	ExpectedRevision *Revision       `json:"expected_revision,omitempty"`
}

type ConfirmationRecord struct {
	ConfirmationID        Id                          `json:"confirmation_id"`
	OwnerID               Id                          `json:"owner_id"`
	Revision              Revision                    `json:"revision"`
	ConsumerMethod        string                      `json:"consumer_method"`
	ConsumerCommandID     Id                          `json:"consumer_command_id"`
	ConsumerTargetID      Id                          `json:"consumer_target_id"`
	ConsumerCommand       ConfirmationConsumerCommand `json:"consumer_command"`
	IntentHash            Digest                      `json:"intent_hash"`
	Challenge             Digest                      `json:"challenge"`
	ExpiresAt             string                      `json:"expires_at"`
	State                 string                      `json:"state"`
	DecidedAt             *string                     `json:"decided_at,omitempty"`
	DecidedBy             *Id                         `json:"decided_by,omitempty"`
	TrustedUserSessionRef *ObjectRef                  `json:"trusted_user_session_ref,omitempty"`
	ConsumedBy            *Id                         `json:"consumed_by,omitempty"`
	ConsumedAt            *string                     `json:"consumed_at,omitempty"`
}

type ContentRef struct {
	TenantID   string `json:"tenant_id"`
	OwnerID    string `json:"owner_id"`
	ContentID  string `json:"content_id"`
	Version    int64  `json:"version"`
	Hash       string `json:"hash"`
	MediaType  string `json:"media_type"`
	ByteLength int64  `json:"byte_length"`
}

type ControlAck struct {
	TaskID             string   `json:"task_id"`
	Revision           int64    `json:"revision"`
	ControlRevision    int64    `json:"control_revision"`
	Status             string   `json:"status"`
	Control            string   `json:"control"`
	PendingExecutorIDs []string `json:"pending_executor_ids"`
	AffectedChildIDs   []string `json:"affected_child_ids"`
}

type ControlSnapshot struct {
	Gate              TaskGate `json:"gate"`
	ExecutorID        string   `json:"executor_id"`
	IssuedAt          string   `json:"issued_at"`
	StartBefore       string   `json:"start_before"`
	OrchestratorProof string   `json:"orchestrator_proof"`
}

type DecisionRecord struct {
	DecisionID       string     `json:"decision_id"`
	Revision         int64      `json:"revision"`
	SnapshotRevision int64      `json:"snapshot_revision"`
	Status           string     `json:"status"`
	Proposal         *Proposal  `json:"proposal,omitempty"`
	ModelCall        *ModelCall `json:"model_call,omitempty"`
	Error            *Error     `json:"error,omitempty"`
}

type DecisionRequest struct {
	DecisionID             string                              `json:"decision_id"`
	TaskID                 string                              `json:"task_id"`
	OrchestratorID         string                              `json:"orchestrator_id"`
	SnapshotRevision       int64                               `json:"snapshot_revision"`
	ContextRef             ContentRef                          `json:"context_ref"`
	CapabilityRefs         []DecisionRequestCapabilityRefsItem `json:"capability_refs"`
	ModelProfileRef        ComponentRef                        `json:"model_profile_ref"`
	Limits                 DecisionRequestLimits               `json:"limits"`
	UsageAuthorizationRefs []AuthorizationRef                  `json:"usage_authorization_refs"`
}

type DecisionRequestCapabilityRefsItem struct {
	CapabilityRef ComponentRef `json:"capability_ref"`
	BindingRef    BindingRef   `json:"binding_ref"`
}

type DecisionRequestLimits struct {
	Deadline           string    `json:"deadline"`
	MaxOutputTokens    int64     `json:"max_output_tokens"`
	MaxActions         int64     `json:"max_actions"`
	MaxContextRequests int64     `json:"max_context_requests"`
	CostReservationRef ObjectRef `json:"cost_reservation_ref"`
}

type DelegationRequest struct {
	DelegationID   string             `json:"delegation_id"`
	ParentTaskID   string             `json:"parent_task_id"`
	AgentBinding   AgentBinding       `json:"agent_binding"`
	GoalRef        ContentRef         `json:"goal_ref"`
	InputRefs      []ContentRef       `json:"input_refs"`
	Constraints    []string           `json:"constraints"`
	Deadline       string             `json:"deadline"`
	AllocationID   string             `json:"allocation_id"`
	PermissionRefs []AuthorizationRef `json:"permission_refs"`
	AncestorIDs    []string           `json:"ancestor_ids"`
}

type Digest = string

type Error struct {
	Code            string  `json:"code"`
	Message         string  `json:"message"`
	Retry           string  `json:"retry"`
	RelatedID       *string `json:"related_id,omitempty"`
	CurrentRevision *int64  `json:"current_revision,omitempty"`
	RetryAfterMs    *int64  `json:"retry_after_ms,omitempty"`
}

type EvaluationApproveInput struct {
	Approval ReleaseApproval `json:"approval"`
}

type EvaluationMetric struct {
	Name      string `json:"name"`
	Direction string `json:"direction"`
	Threshold Amount `json:"threshold"`
	Required  bool   `json:"required"`
}

type GrantIssueInput struct {
	GrantID         Id          `json:"grant_id"`
	Policy          GrantPolicy `json:"policy"`
	IntentHash      Digest      `json:"intent_hash"`
	ConfirmationRef ObjectRef   `json:"confirmation_ref"`
}

type GrantPolicy struct {
	Subject            Subject         `json:"subject"`
	Resources          []ResourceScope `json:"resources"`
	Actions            []string        `json:"actions"`
	Purposes           []string        `json:"purposes"`
	Recipients         []Id            `json:"recipients"`
	Locations          []Id            `json:"locations"`
	Mode               string          `json:"mode"`
	ValidFrom          string          `json:"valid_from"`
	ExpiresAt          string          `json:"expires_at"`
	Limits             []BudgetLimit   `json:"limits"`
	MaxOfflineWindowMs int64           `json:"max_offline_window_ms"`
	ParentGrantRef     *ObjectRef      `json:"parent_grant_ref,omitempty"`
}

type GuiPrecondition struct {
	ObservationID string    `json:"observation_id"`
	ControlEpoch  int64     `json:"control_epoch"`
	LeaseRef      ObjectRef `json:"lease_ref"`
	MaxAgeMs      int64     `json:"max_age_ms"`
	UiRevision    *int64    `json:"ui_revision,omitempty"`
	Focus         *string   `json:"focus,omitempty"`
}

type Id = string

type InputAnswerContentRef = json.RawMessage

type InputConsumption struct {
	RequestID         string  `json:"request_id"`
	RequestRevision   int64   `json:"request_revision"`
	ConsumedBy        string  `json:"consumed_by"`
	TaskID            string  `json:"task_id"`
	VerificationJobID *string `json:"verification_job_id,omitempty"`
}

type InputRequestView struct {
	RequestID           Id                 `json:"request_id"`
	OwnerID             Id                 `json:"owner_id"`
	Revision            Revision           `json:"revision"`
	Kind                string             `json:"kind"`
	TaskRef             *TaskRef           `json:"task_ref,omitempty"`
	Schema              SurfaceInputSchema `json:"schema"`
	QuestionRef         ContentRef         `json:"question_ref"`
	Deadline            string             `json:"deadline"`
	RequiredContentRefs []ContentRef       `json:"required_content_refs"`
	AllowedActions      []string           `json:"allowed_actions"`
	State               string             `json:"state"`
	ConsumedBy          *Id                `json:"consumed_by,omitempty"`
	GoalRevision        *Revision          `json:"goal_revision,omitempty"`
	CandidateRef        *ContentRef        `json:"candidate_ref,omitempty"`
	CandidateHash       *Digest            `json:"candidate_hash,omitempty"`
}

type InteractionRequestReadInput struct {
	RequestRef ObjectRef `json:"request_ref"`
}

type InteractionRequestReadOutput struct {
	Request InputRequestView `json:"request"`
	Gaps    []string         `json:"gaps"`
}

type Invoke struct {
	OperationID       string                     `json:"operation_id"`
	TaskID            string                     `json:"task_id"`
	OrchestratorID    string                     `json:"orchestrator_id"`
	GoalRevision      int64                      `json:"goal_revision"`
	ControlSnapshot   ControlSnapshot            `json:"control_snapshot"`
	CapabilityRef     ComponentRef               `json:"capability_ref"`
	BindingRef        BindingRef                 `json:"binding_ref"`
	Arguments         map[string]json.RawMessage `json:"arguments"`
	IntentHash        string                     `json:"intent_hash"`
	AuthorizationRefs []AuthorizationRef         `json:"authorization_refs"`
	ReservationRef    ObjectRef                  `json:"reservation_ref"`
	Deadline          string                     `json:"deadline"`
	GUIPrecondition   *GuiPrecondition           `json:"gui_precondition,omitempty"`
}

type JobAck struct {
	JobID      string `json:"job_id"`
	ResourceID string `json:"resource_id"`
}

type LeaseAllocationInput struct {
	LeaseID         Id          `json:"lease_id"`
	GrantRefs       []ObjectRef `json:"grant_refs"`
	EndpointID      Id          `json:"endpoint_id"`
	InstanceID      Id          `json:"instance_id"`
	Scope           GrantPolicy `json:"scope"`
	AllocatedUnits  Amount      `json:"allocated_units"`
	AllocatedCost   Amount      `json:"allocated_cost"`
	ExpiresAt       string      `json:"expires_at"`
	ConfirmationRef ObjectRef   `json:"confirmation_ref"`
}

type ModelCall struct {
	ModelCallID       string   `json:"model_call_id"`
	ProviderRequestID *string  `json:"provider_request_id,omitempty"`
	State             string   `json:"state"`
	Usage             []Amount `json:"usage"`
	UsageFinal        bool     `json:"usage_final"`
}

type ObjectRef struct {
	OwnerID  string `json:"owner_id"`
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
}

type Operation struct {
	OperationID      string          `json:"operation_id"`
	Revision         int64           `json:"revision"`
	ExecutionState   string          `json:"execution_state"`
	Effect           string          `json:"effect"`
	MayApplyLater    json.RawMessage `json:"may_apply_later"`
	Attempts         []Attempt       `json:"attempts"`
	TargetReceiptRef *ContentRef     `json:"target_receipt_ref,omitempty"`
	EvidenceRefs     []ContentRef    `json:"evidence_refs"`
	ResultRef        *ContentRef     `json:"result_ref,omitempty"`
	Usage            []Amount        `json:"usage"`
	UsageFinal       bool            `json:"usage_final"`
	NextAction       string          `json:"next_action"`
}

type PairApproveInput struct {
	UserCode        string       `json:"user_code"`
	Decision        string       `json:"decision"`
	ApprovedScope   PairingScope `json:"approved_scope"`
	ConfirmationRef ObjectRef    `json:"confirmation_ref"`
}

type PairingScope struct {
	CapabilityIDs      []Id            `json:"capability_ids"`
	ResourceScopes     []ResourceScope `json:"resource_scopes"`
	MaxOfflineWindowMs int64           `json:"max_offline_window_ms"`
}

type PropagationTarget struct {
	EndpointID       Id       `json:"endpoint_id"`
	RequiredRevision Revision `json:"required_revision"`
	EnforcedRevision int64    `json:"enforced_revision"`
	State            string   `json:"state"`
	LastObservedAt   string   `json:"last_observed_at"`
}

type Proposal struct {
	Kind                 string                        `json:"kind"`
	Rationale            string                        `json:"rationale"`
	EvidenceRefs         []ContentRef                  `json:"evidence_refs"`
	Assumptions          []string                      `json:"assumptions"`
	PlanDelta            *ProposalPlanDelta            `json:"plan_delta,omitempty"`
	RequirementsProposal *ProposalRequirementsProposal `json:"requirements_proposal,omitempty"`
	Actions              *[]json.RawMessage            `json:"actions,omitempty"`
	Requests             *[]ProposalRequestsItem       `json:"requests,omitempty"`
	Question             *string                       `json:"question,omitempty"`
	Options              *[]string                     `json:"options,omitempty"`
	RequiredMaterialRefs *[]ContentRef                 `json:"required_material_refs,omitempty"`
	RequirementRefs      *json.RawMessage              `json:"requirement_refs,omitempty"`
	ArtifactRef          *ContentRef                   `json:"artifact_ref,omitempty"`
	CompletionBasis      *string                       `json:"completion_basis,omitempty"`
	AssessmentRefs       *[]ContentRef                 `json:"assessment_refs,omitempty"`
	Reason               *string                       `json:"reason,omitempty"`
	UnmetRequirementRefs *[]string                     `json:"unmet_requirement_refs,omitempty"`
	RecoverableAdvice    *string                       `json:"recoverable_advice,omitempty"`
}

type ProposalPlanDelta struct {
	BasePlanRef *ContentRef `json:"base_plan_ref"`
	NextPlanRef ContentRef  `json:"next_plan_ref"`
}

type ProposalRequestsItem struct {
	RequestKey string   `json:"request_key"`
	Kind       string   `json:"kind"`
	Query      string   `json:"query"`
	ScopeRefs  []string `json:"scope_refs"`
	Reason     string   `json:"reason"`
	MaxItems   int64    `json:"max_items"`
}

type ProposalRequirementsProposal struct {
	BaseGoalRevision int64         `json:"base_goal_revision"`
	Requirements     []Requirement `json:"requirements"`
}

type ReleaseApproval struct {
	ApprovalID          Id                  `json:"approval_id"`
	Revision            Revision            `json:"revision"`
	ReleaseKind         string              `json:"release_kind"`
	CandidateID         Id                  `json:"candidate_id"`
	CandidateDigest     Digest              `json:"candidate_digest"`
	LockID              Id                  `json:"lock_id"`
	ReportID            Id                  `json:"report_id"`
	ReportDigest        Digest              `json:"report_digest"`
	Targets             []Id                `json:"targets"`
	ApprovedBy          Id                  `json:"approved_by"`
	ConfirmationRef     ObjectRef           `json:"confirmation_ref"`
	Batches             []ApprovalBatch     `json:"batches"`
	ExpiresAt           string              `json:"expires_at"`
	MaxOfflineWindowMs  int64               `json:"max_offline_window_ms"`
	RollbackLock        *Id                 `json:"rollback_lock"`
	RollbackApprovalRef *ObjectRef          `json:"rollback_approval_ref,omitempty"`
	State               string              `json:"state"`
	Propagation         []PropagationTarget `json:"propagation"`
}

type Requirement struct {
	RequirementID string       `json:"requirement_id"`
	Kind          string       `json:"kind"`
	SourceRef     ContentRef   `json:"source_ref"`
	RuleRef       ComponentRef `json:"rule_ref"`
	Required      bool         `json:"required"`
}

type ResourceScope struct {
	ResourceOwnerID   string                `json:"resource_owner_id"`
	ResourceType      string                `json:"resource_type"`
	Selector          ResourceScopeSelector `json:"selector"`
	NormalizerVersion string                `json:"normalizer_version"`
}

type ResourceScopeSelector struct {
	ObjectIDs []string `json:"object_ids"`
	Versions  *[]int64 `json:"versions,omitempty"`
}

type Result struct {
	TaskID           string            `json:"task_id"`
	GoalRevision     int64             `json:"goal_revision"`
	ArtifactRefs     []ContentRef      `json:"artifact_refs"`
	CompletionBasis  string            `json:"completion_basis"`
	ConditionResults []ConditionResult `json:"condition_results"`
	Limitations      []string          `json:"limitations"`
	CompletedAt      string            `json:"completed_at"`
}

type Revision = int64

type RuntimeBudgetAllocation struct {
	AllocationID    Id                    `json:"allocation_id"`
	ParentTaskID    Id                    `json:"parent_task_id"`
	OwnerID         Id                    `json:"owner_id"`
	ReceiverID      Id                    `json:"receiver_id"`
	Revision        Revision              `json:"revision"`
	Limits          []BudgetLimit         `json:"limits"`
	ExpiresAt       string                `json:"expires_at"`
	State           string                `json:"state"`
	FinalUsage      []Amount              `json:"final_usage"`
	Closure         *RuntimeBudgetClosure `json:"closure,omitempty"`
	IncidentCauses  *[]string             `json:"incident_causes,omitempty"`
	IncidentPending *bool                 `json:"incident_pending,omitempty"`
}

type RuntimeBudgetClosure struct {
	AllocationID   Id         `json:"allocation_id"`
	ReceiverID     Id         `json:"receiver_id"`
	UsageRevision  Revision   `json:"usage_revision"`
	FinalUsage     []Amount   `json:"final_usage"`
	SpendingClosed bool       `json:"spending_closed"`
	ClosedAt       string     `json:"closed_at"`
	ProofRef       ContentRef `json:"proof_ref"`
}

type RuntimeBudgetReceiver struct {
	AllocationID       Id                    `json:"allocation_id"`
	ParentOwnerID      Id                    `json:"parent_owner_id"`
	ReceiverID         Id                    `json:"receiver_id"`
	ParentDelegationID Id                    `json:"parent_delegation_id"`
	Revision           Revision              `json:"revision"`
	State              string                `json:"state"`
	TaskID             *Id                   `json:"task_id,omitempty"`
	FinalUsage         []Amount              `json:"final_usage"`
	Closure            *RuntimeBudgetClosure `json:"closure,omitempty"`
}

type RuntimeDelegationContext struct {
	SenderOrchestratorID Id                 `json:"sender_orchestrator_id"`
	ParentDelegationID   Id                 `json:"parent_delegation_id"`
	AllocationRef        ObjectRef          `json:"allocation_ref"`
	AllocationCommandID  Id                 `json:"allocation_command_id"`
	PermissionRefs       []AuthorizationRef `json:"permission_refs"`
	AncestorIDs          []Id               `json:"ancestor_ids"`
}

type RuntimeTaskListCursor struct {
	UpperBound    string `json:"upper_bound"`
	LastCreatedAt string `json:"last_created_at"`
	LastTaskID    Id     `json:"last_task_id"`
}

type Subject struct {
	TenantID      string     `json:"tenant_id"`
	ActorID       string     `json:"actor_id"`
	ActorKind     string     `json:"actor_kind"`
	EndpointID    *string    `json:"endpoint_id,omitempty"`
	TaskID        *string    `json:"task_id,omitempty"`
	DelegationRef *ObjectRef `json:"delegation_ref,omitempty"`
}

type SurfaceField struct {
	Name       string                     `json:"name"`
	Label      string                     `json:"label"`
	Type       string                     `json:"type"`
	Required   bool                       `json:"required"`
	MaxLength  *int64                     `json:"max_length,omitempty"`
	Minimum    *int64                     `json:"minimum,omitempty"`
	Maximum    *int64                     `json:"maximum,omitempty"`
	Options    *[]SurfaceFieldOptionsItem `json:"options,omitempty"`
	MaxChoices *int64                     `json:"max_choices,omitempty"`
}

type SurfaceFieldOptionsItem struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

type SurfaceInputSchema struct {
	Fields []SurfaceField `json:"fields"`
}

type Task struct {
	TenantID        string          `json:"tenant_id"`
	TaskID          string          `json:"task_id"`
	OrchestratorID  string          `json:"orchestrator_id"`
	SubmitCommandID string          `json:"submit_command_id"`
	GoalRef         ContentRef      `json:"goal_ref"`
	GoalRevision    int64           `json:"goal_revision"`
	Requirements    []Requirement   `json:"requirements"`
	PolicyRef       ComponentRef    `json:"policy_ref"`
	Revision        int64           `json:"revision"`
	ControlRevision int64           `json:"control_revision"`
	Status          string          `json:"status"`
	Control         string          `json:"control"`
	WaitReasons     []WaitReason    `json:"wait_reasons"`
	Deadline        string          `json:"deadline"`
	Budget          []BudgetBalance `json:"budget"`
	OpenEffects     []string        `json:"open_effects"`
	AccountingOpen  bool            `json:"accounting_open"`
	ResultRef       *ContentRef     `json:"result_ref,omitempty"`
}

type TaskAcceptResultInput struct {
	RequestID       string    `json:"request_id"`
	RequestRevision int64     `json:"request_revision"`
	CandidateHash   string    `json:"candidate_hash"`
	GoalRevision    int64     `json:"goal_revision"`
	Decision        string    `json:"decision"`
	ConfirmationRef ObjectRef `json:"confirmation_ref"`
}

type TaskAcceptResultOutput = InputConsumption

type TaskAdjustBudgetInput struct {
	Limits []BudgetLimit `json:"limits"`
}

type TaskAdjustBudgetOutput = Task

type TaskAttachEvidenceInput struct {
	OperationID  string       `json:"operation_id"`
	EvidenceRefs []ContentRef `json:"evidence_refs"`
}

type TaskAttachEvidenceOutput = JobAck

type TaskBillingReconcileInput struct {
	SourceKind    string   `json:"source_kind"`
	SourceID      Id       `json:"source_id"`
	UsageRevision Revision `json:"usage_revision"`
	UsageDigest   Digest   `json:"usage_digest"`
}

type TaskBillingReconcileOutput = JobAck

type TaskCancelInput struct {
	Reason string `json:"reason"`
}

type TaskCancelOutput = ControlAck

type TaskGate struct {
	OrchestratorID  string `json:"orchestrator_id"`
	TaskID          string `json:"task_id"`
	ControlRevision int64  `json:"control_revision"`
	GoalRevision    int64  `json:"goal_revision"`
	Status          string `json:"status"`
	Control         string `json:"control"`
}

type TaskInputInput struct {
	RequestID       string                `json:"request_id"`
	RequestRevision int64                 `json:"request_revision"`
	AnswerRef       InputAnswerContentRef `json:"answer_ref"`
	PreviewRefs     []ContentRef          `json:"preview_refs"`
}

type TaskInputOutput = InputConsumption

type TaskListInput struct {
	Limit    int64                  `json:"limit"`
	Statuses *[]string              `json:"statuses,omitempty"`
	Cursor   *RuntimeTaskListCursor `json:"cursor,omitempty"`
}

type TaskListOutput struct {
	OrchestratorID Id                        `json:"orchestrator_id"`
	UpperBound     string                    `json:"upper_bound"`
	Items          []TaskListOutputItemsItem `json:"items"`
	NextCursor     *RuntimeTaskListCursor    `json:"next_cursor,omitempty"`
	Gaps           []string                  `json:"gaps"`
}

type TaskListOutputItemsItem struct {
	CreatedAt string `json:"created_at"`
	Task      Task   `json:"task"`
}

type TaskPauseInput struct {
	Reason string `json:"reason"`
}

type TaskPauseOutput = ControlAck

type TaskReadInput struct {
}

type TaskReadOutput = Task

type TaskRef struct {
	OrchestratorID string `json:"orchestrator_id"`
	TaskID         string `json:"task_id"`
}

type TaskResultInput struct {
}

type TaskResultOutput = TaskResultView

type TaskResultView struct {
	Status                 string    `json:"status"`
	Result                 *Result   `json:"result,omitempty"`
	Reason                 *string   `json:"reason,omitempty"`
	UnresolvedOperationIDs *[]string `json:"unresolved_operation_ids,omitempty"`
	AccountingOpen         *bool     `json:"accounting_open,omitempty"`
}

type TaskResumeInput struct {
	Reason string `json:"reason"`
}

type TaskResumeOutput = ControlAck

type TaskReviseInput struct {
	GoalRef     ContentRef `json:"goal_ref"`
	Constraints []string   `json:"constraints"`
}

type TaskReviseOutput = Task

type TaskSubmitInput struct {
	GoalRef           ContentRef                `json:"goal_ref"`
	OrchestratorID    string                    `json:"orchestrator_id"`
	Constraints       []string                  `json:"constraints"`
	PolicyRef         ComponentRef              `json:"policy_ref"`
	Budget            []BudgetLimit             `json:"budget"`
	Deadline          string                    `json:"deadline"`
	DelegationContext *RuntimeDelegationContext `json:"delegation_context,omitempty"`
}

type TaskSubmitOutput = Task

type WaitReason struct {
	Kind            string     `json:"kind"`
	ObjectRef       *ObjectRef `json:"object_ref,omitempty"`
	ResumeCondition string     `json:"resume_condition"`
	Deadline        *string    `json:"deadline,omitempty"`
}
